// Code generated by ent, DO NOT EDIT.

package ledgeraccount

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/suda-3156/kkb/go/ent/schema"
)

const (
	// Label holds the string label denoting the ledgeraccount type in the database.
	Label = "ledger_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldAccountName holds the string denoting the account_name field in the database.
	FieldAccountName = "account_name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldIsGroup holds the string denoting the is_group field in the database.
	FieldIsGroup = "is_group"
	// FieldArchivedAt holds the string denoting the archived_at field in the database.
	FieldArchivedAt = "archived_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgeJournalEntries holds the string denoting the journal_entries edge name in mutations.
	EdgeJournalEntries = "journal_entries"
	// EdgeEncryptionKey holds the string denoting the encryption_key edge name in mutations.
	EdgeEncryptionKey = "encryption_key"
	// Table holds the table name of the ledgeraccount in the database.
	Table = "ledger_accounts"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "ledger_accounts"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "ledger_account_children"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "ledger_accounts"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "ledger_account_children"
	// JournalEntriesTable is the table that holds the journal_entries relation/edge.
	JournalEntriesTable = "journal_entries"
	// JournalEntriesInverseTable is the table name for the JournalEntry entity.
	// It exists in this package in order to avoid circular dependency with the "journalentry" package.
	JournalEntriesInverseTable = "journal_entries"
	// JournalEntriesColumn is the table column denoting the journal_entries relation/edge.
	JournalEntriesColumn = "ledger_account_journal_entries"
	// EncryptionKeyTable is the table that holds the encryption_key relation/edge.
	EncryptionKeyTable = "ledger_accounts"
	// EncryptionKeyInverseTable is the table name for the LedgerEncryptionKey entity.
	// It exists in this package in order to avoid circular dependency with the "ledgerencryptionkey" package.
	EncryptionKeyInverseTable = "ledger_encryption_keys"
	// EncryptionKeyColumn is the table column denoting the encryption_key relation/edge.
	EncryptionKeyColumn = "ledger_encryption_key_ledger_accounts"
)

// Columns holds all SQL columns for ledgeraccount fields.
var Columns = []string{
	FieldID,
	FieldPublicID,
	FieldAccountName,
	FieldKind,
	FieldIsGroup,
	FieldArchivedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ledger_accounts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ledger_account_children",
	"ledger_encryption_key_ledger_accounts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	AccountNameValidator func([]byte) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k schema.LedgerAccountKind) error {
	switch k {
	case "ASSET", "LIABILITY", "EXPENSE", "REVENUE", "EQUITY":
		return nil
	default:
		return fmt.Errorf("ledgeraccount: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the LedgerAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByIsGroup orders the results by the is_group field.
func ByIsGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsGroup, opts...).ToFunc()
}

// ByArchivedAt orders the results by the archived_at field.
func ByArchivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchivedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByJournalEntriesCount orders the results by journal_entries count.
func ByJournalEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newJournalEntriesStep(), opts...)
	}
}

// ByJournalEntries orders the results by journal_entries terms.
func ByJournalEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJournalEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEncryptionKeyField orders the results by encryption_key field.
func ByEncryptionKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEncryptionKeyStep(), sql.OrderByField(field, opts...))
	}
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
func newJournalEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JournalEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, JournalEntriesTable, JournalEntriesColumn),
	)
}
func newEncryptionKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EncryptionKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EncryptionKeyTable, EncryptionKeyColumn),
	)
}
