// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/internal/date"
	"github.com/suda-3156/kkb/go/internal/prid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPublicID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v []byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldName, v))
}

// RegisteredOn applies equality check predicate on the "registered_on" field. It's identical to RegisteredOnEQ.
func RegisteredOn(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldRegisteredOn, vc))
}

// AnchorOn applies equality check predicate on the "anchor_on" field. It's identical to AnchorOnEQ.
func AnchorOn(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldAnchorOn, vc))
}

// NextOccurrenceOn applies equality check predicate on the "next_occurrence_on" field. It's identical to NextOccurrenceOnEQ.
func NextOccurrenceOn(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldNextOccurrenceOn, vc))
}

// CoveredThroughOn applies equality check predicate on the "covered_through_on" field. It's identical to CoveredThroughOnEQ.
func CoveredThroughOn(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldCoveredThroughOn, vc))
}

// IntervalMonths applies equality check predicate on the "interval_months" field. It's identical to IntervalMonthsEQ.
func IntervalMonths(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldIntervalMonths, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v prid.ID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v prid.ID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContains(FieldPublicID, vc))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v prid.ID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasPrefix(FieldPublicID, vc))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v prid.ID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasSuffix(FieldPublicID, vc))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v prid.ID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEqualFold(FieldPublicID, vc))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v prid.ID) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContainsFold(FieldPublicID, vc))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v []byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v []byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...[]byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...[]byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v []byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v []byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v []byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v []byte) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldName, v))
}

// RegisteredOnEQ applies the EQ predicate on the "registered_on" field.
func RegisteredOnEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldRegisteredOn, vc))
}

// RegisteredOnNEQ applies the NEQ predicate on the "registered_on" field.
func RegisteredOnNEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldNEQ(FieldRegisteredOn, vc))
}

// RegisteredOnIn applies the In predicate on the "registered_on" field.
func RegisteredOnIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldIn(FieldRegisteredOn, v...))
}

// RegisteredOnNotIn applies the NotIn predicate on the "registered_on" field.
func RegisteredOnNotIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldNotIn(FieldRegisteredOn, v...))
}

// RegisteredOnGT applies the GT predicate on the "registered_on" field.
func RegisteredOnGT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGT(FieldRegisteredOn, vc))
}

// RegisteredOnGTE applies the GTE predicate on the "registered_on" field.
func RegisteredOnGTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGTE(FieldRegisteredOn, vc))
}

// RegisteredOnLT applies the LT predicate on the "registered_on" field.
func RegisteredOnLT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLT(FieldRegisteredOn, vc))
}

// RegisteredOnLTE applies the LTE predicate on the "registered_on" field.
func RegisteredOnLTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLTE(FieldRegisteredOn, vc))
}

// RegisteredOnContains applies the Contains predicate on the "registered_on" field.
func RegisteredOnContains(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContains(FieldRegisteredOn, vc))
}

// RegisteredOnHasPrefix applies the HasPrefix predicate on the "registered_on" field.
func RegisteredOnHasPrefix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasPrefix(FieldRegisteredOn, vc))
}

// RegisteredOnHasSuffix applies the HasSuffix predicate on the "registered_on" field.
func RegisteredOnHasSuffix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasSuffix(FieldRegisteredOn, vc))
}

// RegisteredOnEqualFold applies the EqualFold predicate on the "registered_on" field.
func RegisteredOnEqualFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEqualFold(FieldRegisteredOn, vc))
}

// RegisteredOnContainsFold applies the ContainsFold predicate on the "registered_on" field.
func RegisteredOnContainsFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContainsFold(FieldRegisteredOn, vc))
}

// AnchorOnEQ applies the EQ predicate on the "anchor_on" field.
func AnchorOnEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldAnchorOn, vc))
}

// AnchorOnNEQ applies the NEQ predicate on the "anchor_on" field.
func AnchorOnNEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldNEQ(FieldAnchorOn, vc))
}

// AnchorOnIn applies the In predicate on the "anchor_on" field.
func AnchorOnIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldIn(FieldAnchorOn, v...))
}

// AnchorOnNotIn applies the NotIn predicate on the "anchor_on" field.
func AnchorOnNotIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldNotIn(FieldAnchorOn, v...))
}

// AnchorOnGT applies the GT predicate on the "anchor_on" field.
func AnchorOnGT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGT(FieldAnchorOn, vc))
}

// AnchorOnGTE applies the GTE predicate on the "anchor_on" field.
func AnchorOnGTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGTE(FieldAnchorOn, vc))
}

// AnchorOnLT applies the LT predicate on the "anchor_on" field.
func AnchorOnLT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLT(FieldAnchorOn, vc))
}

// AnchorOnLTE applies the LTE predicate on the "anchor_on" field.
func AnchorOnLTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLTE(FieldAnchorOn, vc))
}

// AnchorOnContains applies the Contains predicate on the "anchor_on" field.
func AnchorOnContains(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContains(FieldAnchorOn, vc))
}

// AnchorOnHasPrefix applies the HasPrefix predicate on the "anchor_on" field.
func AnchorOnHasPrefix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasPrefix(FieldAnchorOn, vc))
}

// AnchorOnHasSuffix applies the HasSuffix predicate on the "anchor_on" field.
func AnchorOnHasSuffix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasSuffix(FieldAnchorOn, vc))
}

// AnchorOnEqualFold applies the EqualFold predicate on the "anchor_on" field.
func AnchorOnEqualFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEqualFold(FieldAnchorOn, vc))
}

// AnchorOnContainsFold applies the ContainsFold predicate on the "anchor_on" field.
func AnchorOnContainsFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContainsFold(FieldAnchorOn, vc))
}

// NextOccurrenceOnEQ applies the EQ predicate on the "next_occurrence_on" field.
func NextOccurrenceOnEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnNEQ applies the NEQ predicate on the "next_occurrence_on" field.
func NextOccurrenceOnNEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldNEQ(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnIn applies the In predicate on the "next_occurrence_on" field.
func NextOccurrenceOnIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldIn(FieldNextOccurrenceOn, v...))
}

// NextOccurrenceOnNotIn applies the NotIn predicate on the "next_occurrence_on" field.
func NextOccurrenceOnNotIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldNotIn(FieldNextOccurrenceOn, v...))
}

// NextOccurrenceOnGT applies the GT predicate on the "next_occurrence_on" field.
func NextOccurrenceOnGT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGT(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnGTE applies the GTE predicate on the "next_occurrence_on" field.
func NextOccurrenceOnGTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGTE(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnLT applies the LT predicate on the "next_occurrence_on" field.
func NextOccurrenceOnLT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLT(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnLTE applies the LTE predicate on the "next_occurrence_on" field.
func NextOccurrenceOnLTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLTE(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnContains applies the Contains predicate on the "next_occurrence_on" field.
func NextOccurrenceOnContains(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContains(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnHasPrefix applies the HasPrefix predicate on the "next_occurrence_on" field.
func NextOccurrenceOnHasPrefix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasPrefix(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnHasSuffix applies the HasSuffix predicate on the "next_occurrence_on" field.
func NextOccurrenceOnHasSuffix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasSuffix(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnEqualFold applies the EqualFold predicate on the "next_occurrence_on" field.
func NextOccurrenceOnEqualFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEqualFold(FieldNextOccurrenceOn, vc))
}

// NextOccurrenceOnContainsFold applies the ContainsFold predicate on the "next_occurrence_on" field.
func NextOccurrenceOnContainsFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContainsFold(FieldNextOccurrenceOn, vc))
}

// CoveredThroughOnEQ applies the EQ predicate on the "covered_through_on" field.
func CoveredThroughOnEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEQ(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnNEQ applies the NEQ predicate on the "covered_through_on" field.
func CoveredThroughOnNEQ(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldNEQ(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnIn applies the In predicate on the "covered_through_on" field.
func CoveredThroughOnIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldIn(FieldCoveredThroughOn, v...))
}

// CoveredThroughOnNotIn applies the NotIn predicate on the "covered_through_on" field.
func CoveredThroughOnNotIn(vs ...date.Date) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Subscription(sql.FieldNotIn(FieldCoveredThroughOn, v...))
}

// CoveredThroughOnGT applies the GT predicate on the "covered_through_on" field.
func CoveredThroughOnGT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGT(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnGTE applies the GTE predicate on the "covered_through_on" field.
func CoveredThroughOnGTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldGTE(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnLT applies the LT predicate on the "covered_through_on" field.
func CoveredThroughOnLT(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLT(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnLTE applies the LTE predicate on the "covered_through_on" field.
func CoveredThroughOnLTE(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldLTE(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnContains applies the Contains predicate on the "covered_through_on" field.
func CoveredThroughOnContains(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContains(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnHasPrefix applies the HasPrefix predicate on the "covered_through_on" field.
func CoveredThroughOnHasPrefix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasPrefix(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnHasSuffix applies the HasSuffix predicate on the "covered_through_on" field.
func CoveredThroughOnHasSuffix(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldHasSuffix(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnEqualFold applies the EqualFold predicate on the "covered_through_on" field.
func CoveredThroughOnEqualFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldEqualFold(FieldCoveredThroughOn, vc))
}

// CoveredThroughOnContainsFold applies the ContainsFold predicate on the "covered_through_on" field.
func CoveredThroughOnContainsFold(v date.Date) predicate.Subscription {
	vc := string(v)
	return predicate.Subscription(sql.FieldContainsFold(FieldCoveredThroughOn, vc))
}

// IntervalMonthsEQ applies the EQ predicate on the "interval_months" field.
func IntervalMonthsEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldIntervalMonths, v))
}

// IntervalMonthsNEQ applies the NEQ predicate on the "interval_months" field.
func IntervalMonthsNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldIntervalMonths, v))
}

// IntervalMonthsIn applies the In predicate on the "interval_months" field.
func IntervalMonthsIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldIntervalMonths, vs...))
}

// IntervalMonthsNotIn applies the NotIn predicate on the "interval_months" field.
func IntervalMonthsNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldIntervalMonths, vs...))
}

// IntervalMonthsGT applies the GT predicate on the "interval_months" field.
func IntervalMonthsGT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldIntervalMonths, v))
}

// IntervalMonthsGTE applies the GTE predicate on the "interval_months" field.
func IntervalMonthsGTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldIntervalMonths, v))
}

// IntervalMonthsLT applies the LT predicate on the "interval_months" field.
func IntervalMonthsLT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldIntervalMonths, v))
}

// IntervalMonthsLTE applies the LTE predicate on the "interval_months" field.
func IntervalMonthsLTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldIntervalMonths, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v schema.SubscriptionStatus) predicate.Subscription {
	vc := v
	return predicate.Subscription(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v schema.SubscriptionStatus) predicate.Subscription {
	vc := v
	return predicate.Subscription(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...schema.SubscriptionStatus) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Subscription(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...schema.SubscriptionStatus) predicate.Subscription {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Subscription(sql.FieldNotIn(FieldStatus, v...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTemplateEntries applies the HasEdge predicate on the "template_entries" edge.
func HasTemplateEntries() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TemplateEntriesTable, TemplateEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTemplateEntriesWith applies the HasEdge predicate on the "template_entries" edge with a given conditions (other predicates).
func HasTemplateEntriesWith(preds ...predicate.SubscriptionEntry) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newTemplateEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOccurrences applies the HasEdge predicate on the "occurrences" edge.
func HasOccurrences() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OccurrencesTable, OccurrencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOccurrencesWith applies the HasEdge predicate on the "occurrences" edge with a given conditions (other predicates).
func HasOccurrencesWith(preds ...predicate.SubscriptionOccurrence) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newOccurrencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTransactions applies the HasEdge predicate on the "transactions" edge.
func HasTransactions() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTransactionsWith applies the HasEdge predicate on the "transactions" edge with a given conditions (other predicates).
func HasTransactionsWith(preds ...predicate.Transaction) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newTransactionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEncryptionKey applies the HasEdge predicate on the "encryption_key" edge.
func HasEncryptionKey() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EncryptionKeyTable, EncryptionKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEncryptionKeyWith applies the HasEdge predicate on the "encryption_key" edge with a given conditions (other predicates).
func HasEncryptionKeyWith(preds ...predicate.LedgerEncryptionKey) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newEncryptionKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.NotPredicates(p))
}
