package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/suda-3156/kkb/go/graph"
	"github.com/suda-3156/kkb/go/graph/model"
	pulid1 "github.com/suda-3156/kkb/go/internal/pulid"
)

// HealthCheck is the resolver for the healthCheck field.
func (r *queryResolver) HealthCheck(ctx context.Context) (string, error) {
	return fmt.Sprintf("OK - %s", time.Now().Format("2006-01-02 15:04:05")), nil
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id pulid1.ID) (model.Node, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
