package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"

	"github.com/suda-3156/kkb/go/graph"
	"github.com/suda-3156/kkb/go/graph/model"
	"github.com/suda-3156/kkb/go/internal/dataloader"
	"github.com/suda-3156/kkb/go/internal/date"
	ledgeraccount "github.com/suda-3156/kkb/go/internal/ledger_account"
	"github.com/suda-3156/kkb/go/internal/prid"
)

// Parent is the resolver for the parent field.
func (r *ledgerAccountResolver) Parent(ctx context.Context, obj *model.LedgerAccount) (*model.LedgerAccount, error) {
	if obj.Parent == nil {
		return nil, nil
	}
	thunk := dataloader.For(ctx).LedgerAccountLoader.Load(ctx, obj.Parent.IntID)
	lac, err := thunk()
	if err != nil {
		return nil, err
	}
	return lac, nil
}

// LastUsedAt is the resolver for the lastUsedAt field.
func (r *ledgerAccountResolver) LastUsedAt(ctx context.Context, obj *model.LedgerAccount) (*date.Date, error) {
	lastUsed, err := r.lastUsed(ctx, obj)
	if err != nil || lastUsed == nil {
		return nil, err
	}
	return &lastUsed.Date, nil
}

// LastRecordedAt is the resolver for the lastRecordedAt field.
func (r *ledgerAccountResolver) LastRecordedAt(ctx context.Context, obj *model.LedgerAccount) (*time.Time, error) {
	lastUsed, err := r.lastUsed(ctx, obj)
	if err != nil || lastUsed == nil {
		return nil, err
	}
	return &lastUsed.RecordedAt, nil
}

// lastUsed loads the last use of one account. Both fields go through the same
// loader, so asking for both costs one query for the whole list, not two.
// A never-used account yields nil, which both fields render as null.
func (r *ledgerAccountResolver) lastUsed(
	ctx context.Context,
	obj *model.LedgerAccount,
) (*ledgeraccount.LastUsed, error) {
	thunk := dataloader.For(ctx).LedgerAccountLastUsedLoader.Load(ctx, obj.IntID)
	return thunk()
}

// CreateLedgerAccount is the resolver for the createLedgerAccount field.
func (r *mutationResolver) CreateLedgerAccount(ctx context.Context, input model.CreateLedgerAccountInput) (*model.LedgerAccount, error) {
	return r.lac.Create(ctx, input)
}

// UpdateLedgerAccount is the resolver for the updateLedgerAccount field.
func (r *mutationResolver) UpdateLedgerAccount(ctx context.Context, input model.UpdateLedgerAccountInput) (*model.LedgerAccount, error) {
	return r.lac.Update(ctx, input)
}

// ArchiveLedgerAccount is the resolver for the archiveLedgerAccount field.
func (r *mutationResolver) ArchiveLedgerAccount(ctx context.Context, id prid.ID) (*model.LedgerAccount, error) {
	return r.lac.Archive(ctx, id)
}

// UnarchiveLedgerAccount is the resolver for the unarchiveLedgerAccount field.
func (r *mutationResolver) UnarchiveLedgerAccount(ctx context.Context, id prid.ID) (*model.LedgerAccount, error) {
	return r.lac.Unarchive(ctx, id)
}

// LedgerAccount is the resolver for the ledgerAccount field.
func (r *queryResolver) LedgerAccount(ctx context.Context, id prid.ID) (*model.LedgerAccount, error) {
	return r.lac.GetByPublicID(ctx, id)
}

// LedgerAccounts is the resolver for the ledgerAccounts field.
func (r *queryResolver) LedgerAccounts(ctx context.Context, first *int32, last *int32, kind *model.LedgerAccountKind, includeArchived *bool, after *prid.ID, before *prid.ID) (*model.LedgerAccountConnection, error) {
	filter := &ledgeraccount.Filter{
		First:           first,
		After:           after,
		Last:            last,
		Before:          before,
		Kind:            kind,
		IncludeArchived: includeArchived,
	}

	return r.lac.List(ctx, filter)
}

// LedgerAccount returns graph.LedgerAccountResolver implementation.
func (r *Resolver) LedgerAccount() graph.LedgerAccountResolver { return &ledgerAccountResolver{r} }

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type ledgerAccountResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
