package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/suda-3156/kkb/go/graph"
	"github.com/suda-3156/kkb/go/graph/model"
	"github.com/suda-3156/kkb/go/internal/date"
	pulid1 "github.com/suda-3156/kkb/go/internal/pulid"
)

// LedgerAccount is the resolver for the ledgerAccount field.
func (r *journalEntryResolver) LedgerAccount(ctx context.Context, obj *model.JournalEntry) (*model.LedgerAccount, error) {
	panic(fmt.Errorf("not implemented: LedgerAccount - ledgerAccount"))
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: CreateTransaction - createTransaction"))
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, input model.UpdateTransactionInput) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: UpdateTransaction - updateTransaction"))
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id pulid1.ID) (*model.DeleteTransactionPayload, error) {
	panic(fmt.Errorf("not implemented: DeleteTransaction - deleteTransaction"))
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id pulid1.ID) (*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, first *int32, after *pulid1.ID, last *int32, before *pulid1.ID, startDate *date.Date, endDate *date.Date) (*model.TransactionConnection, error) {
	panic(fmt.Errorf("not implemented: Transactions - transactions"))
}

// JournalEntry returns graph.JournalEntryResolver implementation.
func (r *Resolver) JournalEntry() graph.JournalEntryResolver { return &journalEntryResolver{r} }

type journalEntryResolver struct{ *Resolver }
