services:
  db:
    container_name: ${PROJECT_NAME:?unset (run 'direnv allow' in main/ first)}-db
    image: mysql:9.7@sha256:257388edf9c84dbc04c763625446d5f3fa6ed60d1b0873bc552c614ba0a7ab4e
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
      TZ: ${TZ}
    volumes:
      - app-data:/var/lib/mysql
      - ./db/docker/logs:/var/log/mysql
      - ./db/docker/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    container_name: ${PROJECT_NAME:?unset (run 'direnv allow' in main/ first)}-api
    build:
      context: .
      dockerfile: ./go/Dockerfile
    env_file:
      - ./.env.local
    volumes:
      - ./go:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  app-data:
    name: ${PROJECT_NAME:?unset (run 'direnv allow' in main/ first)}-data

networks:
  app-network:
    name: ${PROJECT_NAME:?unset (run 'direnv allow' in main/ first)}-network
