// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/journalentry"
	"github.com/suda-3156/kkb/go/ent/ledgeraccount"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/transaction"
	"github.com/suda-3156/kkb/go/internal/pulid"
)

// JournalEntryCreate is the builder for creating a JournalEntry entity.
type JournalEntryCreate struct {
	config
	mutation *JournalEntryMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (_c *JournalEntryCreate) SetPublicID(v pulid.ID) *JournalEntryCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *JournalEntryCreate) SetAmount(v []byte) *JournalEntryCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *JournalEntryCreate) SetKind(v schema.JournalEntryKind) *JournalEntryCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *JournalEntryCreate) SetCreatedAt(v time.Time) *JournalEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *JournalEntryCreate) SetNillableCreatedAt(v *time.Time) *JournalEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *JournalEntryCreate) SetUpdatedAt(v time.Time) *JournalEntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *JournalEntryCreate) SetNillableUpdatedAt(v *time.Time) *JournalEntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (_c *JournalEntryCreate) SetTransactionID(id int) *JournalEntryCreate {
	_c.mutation.SetTransactionID(id)
	return _c
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_c *JournalEntryCreate) SetTransaction(v *Transaction) *JournalEntryCreate {
	return _c.SetTransactionID(v.ID)
}

// SetLedgerAccountID sets the "ledger_account" edge to the LedgerAccount entity by ID.
func (_c *JournalEntryCreate) SetLedgerAccountID(id int) *JournalEntryCreate {
	_c.mutation.SetLedgerAccountID(id)
	return _c
}

// SetLedgerAccount sets the "ledger_account" edge to the LedgerAccount entity.
func (_c *JournalEntryCreate) SetLedgerAccount(v *LedgerAccount) *JournalEntryCreate {
	return _c.SetLedgerAccountID(v.ID)
}

// Mutation returns the JournalEntryMutation object of the builder.
func (_c *JournalEntryCreate) Mutation() *JournalEntryMutation {
	return _c.mutation
}

// Save creates the JournalEntry in the database.
func (_c *JournalEntryCreate) Save(ctx context.Context) (*JournalEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JournalEntryCreate) SaveX(ctx context.Context) *JournalEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JournalEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JournalEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JournalEntryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := journalentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := journalentry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JournalEntryCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "JournalEntry.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := journalentry.PublicIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "JournalEntry.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "JournalEntry.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := journalentry.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "JournalEntry.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "JournalEntry.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := journalentry.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "JournalEntry.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "JournalEntry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "JournalEntry.updated_at"`)}
	}
	if len(_c.mutation.TransactionIDs()) == 0 {
		return &ValidationError{Name: "transaction", err: errors.New(`ent: missing required edge "JournalEntry.transaction"`)}
	}
	if len(_c.mutation.LedgerAccountIDs()) == 0 {
		return &ValidationError{Name: "ledger_account", err: errors.New(`ent: missing required edge "JournalEntry.ledger_account"`)}
	}
	return nil
}

func (_c *JournalEntryCreate) sqlSave(ctx context.Context) (*JournalEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JournalEntryCreate) createSpec() (*JournalEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &JournalEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(journalentry.Table, sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(journalentry.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(journalentry.FieldAmount, field.TypeBytes, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(journalentry.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(journalentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(journalentry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.TransactionTable,
			Columns: []string{journalentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.transaction_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgerAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.LedgerAccountTable,
			Columns: []string{journalentry.LedgerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_account_journal_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// JournalEntryCreateBulk is the builder for creating many JournalEntry entities in bulk.
type JournalEntryCreateBulk struct {
	config
	err      error
	builders []*JournalEntryCreate
}

// Save creates the JournalEntry entities in the database.
func (_c *JournalEntryCreateBulk) Save(ctx context.Context) ([]*JournalEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*JournalEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JournalEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JournalEntryCreateBulk) SaveX(ctx context.Context) []*JournalEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JournalEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JournalEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
