// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/journalentry"
	"github.com/suda-3156/kkb/go/ent/ledgeraccount"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/transaction"
)

// JournalEntryUpdate is the builder for updating JournalEntry entities.
type JournalEntryUpdate struct {
	config
	hooks    []Hook
	mutation *JournalEntryMutation
}

// Where appends a list predicates to the JournalEntryUpdate builder.
func (_u *JournalEntryUpdate) Where(ps ...predicate.JournalEntry) *JournalEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *JournalEntryUpdate) SetAmount(v []byte) *JournalEntryUpdate {
	_u.mutation.SetAmount(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *JournalEntryUpdate) SetKind(v schema.JournalEntryKind) *JournalEntryUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *JournalEntryUpdate) SetNillableKind(v *schema.JournalEntryKind) *JournalEntryUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JournalEntryUpdate) SetUpdatedAt(v time.Time) *JournalEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (_u *JournalEntryUpdate) SetTransactionID(id int) *JournalEntryUpdate {
	_u.mutation.SetTransactionID(id)
	return _u
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_u *JournalEntryUpdate) SetTransaction(v *Transaction) *JournalEntryUpdate {
	return _u.SetTransactionID(v.ID)
}

// SetLedgerAccountID sets the "ledger_account" edge to the LedgerAccount entity by ID.
func (_u *JournalEntryUpdate) SetLedgerAccountID(id int) *JournalEntryUpdate {
	_u.mutation.SetLedgerAccountID(id)
	return _u
}

// SetLedgerAccount sets the "ledger_account" edge to the LedgerAccount entity.
func (_u *JournalEntryUpdate) SetLedgerAccount(v *LedgerAccount) *JournalEntryUpdate {
	return _u.SetLedgerAccountID(v.ID)
}

// Mutation returns the JournalEntryMutation object of the builder.
func (_u *JournalEntryUpdate) Mutation() *JournalEntryMutation {
	return _u.mutation
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (_u *JournalEntryUpdate) ClearTransaction() *JournalEntryUpdate {
	_u.mutation.ClearTransaction()
	return _u
}

// ClearLedgerAccount clears the "ledger_account" edge to the LedgerAccount entity.
func (_u *JournalEntryUpdate) ClearLedgerAccount() *JournalEntryUpdate {
	_u.mutation.ClearLedgerAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JournalEntryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JournalEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JournalEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JournalEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JournalEntryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := journalentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JournalEntryUpdate) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := journalentry.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "JournalEntry.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := journalentry.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "JournalEntry.kind": %w`, err)}
		}
	}
	if _u.mutation.TransactionCleared() && len(_u.mutation.TransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JournalEntry.transaction"`)
	}
	if _u.mutation.LedgerAccountCleared() && len(_u.mutation.LedgerAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JournalEntry.ledger_account"`)
	}
	return nil
}

func (_u *JournalEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(journalentry.Table, journalentry.Columns, sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(journalentry.FieldAmount, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(journalentry.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(journalentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.TransactionTable,
			Columns: []string{journalentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.TransactionTable,
			Columns: []string{journalentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.LedgerAccountTable,
			Columns: []string{journalentry.LedgerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.LedgerAccountTable,
			Columns: []string{journalentry.LedgerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journalentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JournalEntryUpdateOne is the builder for updating a single JournalEntry entity.
type JournalEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JournalEntryMutation
}

// SetAmount sets the "amount" field.
func (_u *JournalEntryUpdateOne) SetAmount(v []byte) *JournalEntryUpdateOne {
	_u.mutation.SetAmount(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *JournalEntryUpdateOne) SetKind(v schema.JournalEntryKind) *JournalEntryUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *JournalEntryUpdateOne) SetNillableKind(v *schema.JournalEntryKind) *JournalEntryUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JournalEntryUpdateOne) SetUpdatedAt(v time.Time) *JournalEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTransactionID sets the "transaction" edge to the Transaction entity by ID.
func (_u *JournalEntryUpdateOne) SetTransactionID(id int) *JournalEntryUpdateOne {
	_u.mutation.SetTransactionID(id)
	return _u
}

// SetTransaction sets the "transaction" edge to the Transaction entity.
func (_u *JournalEntryUpdateOne) SetTransaction(v *Transaction) *JournalEntryUpdateOne {
	return _u.SetTransactionID(v.ID)
}

// SetLedgerAccountID sets the "ledger_account" edge to the LedgerAccount entity by ID.
func (_u *JournalEntryUpdateOne) SetLedgerAccountID(id int) *JournalEntryUpdateOne {
	_u.mutation.SetLedgerAccountID(id)
	return _u
}

// SetLedgerAccount sets the "ledger_account" edge to the LedgerAccount entity.
func (_u *JournalEntryUpdateOne) SetLedgerAccount(v *LedgerAccount) *JournalEntryUpdateOne {
	return _u.SetLedgerAccountID(v.ID)
}

// Mutation returns the JournalEntryMutation object of the builder.
func (_u *JournalEntryUpdateOne) Mutation() *JournalEntryMutation {
	return _u.mutation
}

// ClearTransaction clears the "transaction" edge to the Transaction entity.
func (_u *JournalEntryUpdateOne) ClearTransaction() *JournalEntryUpdateOne {
	_u.mutation.ClearTransaction()
	return _u
}

// ClearLedgerAccount clears the "ledger_account" edge to the LedgerAccount entity.
func (_u *JournalEntryUpdateOne) ClearLedgerAccount() *JournalEntryUpdateOne {
	_u.mutation.ClearLedgerAccount()
	return _u
}

// Where appends a list predicates to the JournalEntryUpdate builder.
func (_u *JournalEntryUpdateOne) Where(ps ...predicate.JournalEntry) *JournalEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JournalEntryUpdateOne) Select(field string, fields ...string) *JournalEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated JournalEntry entity.
func (_u *JournalEntryUpdateOne) Save(ctx context.Context) (*JournalEntry, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JournalEntryUpdateOne) SaveX(ctx context.Context) *JournalEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JournalEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JournalEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JournalEntryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := journalentry.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JournalEntryUpdateOne) check() error {
	if v, ok := _u.mutation.Amount(); ok {
		if err := journalentry.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "JournalEntry.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := journalentry.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "JournalEntry.kind": %w`, err)}
		}
	}
	if _u.mutation.TransactionCleared() && len(_u.mutation.TransactionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JournalEntry.transaction"`)
	}
	if _u.mutation.LedgerAccountCleared() && len(_u.mutation.LedgerAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JournalEntry.ledger_account"`)
	}
	return nil
}

func (_u *JournalEntryUpdateOne) sqlSave(ctx context.Context) (_node *JournalEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(journalentry.Table, journalentry.Columns, sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JournalEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, journalentry.FieldID)
		for _, f := range fields {
			if !journalentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != journalentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(journalentry.FieldAmount, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(journalentry.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(journalentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TransactionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.TransactionTable,
			Columns: []string{journalentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.TransactionTable,
			Columns: []string{journalentry.TransactionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LedgerAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.LedgerAccountTable,
			Columns: []string{journalentry.LedgerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.LedgerAccountTable,
			Columns: []string{journalentry.LedgerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &JournalEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journalentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
