// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/ledgerencryptionkey"
	"github.com/suda-3156/kkb/go/ent/predicate"
)

// LedgerEncryptionKeyDelete is the builder for deleting a LedgerEncryptionKey entity.
type LedgerEncryptionKeyDelete struct {
	config
	hooks    []Hook
	mutation *LedgerEncryptionKeyMutation
}

// Where appends a list predicates to the LedgerEncryptionKeyDelete builder.
func (_d *LedgerEncryptionKeyDelete) Where(ps ...predicate.LedgerEncryptionKey) *LedgerEncryptionKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LedgerEncryptionKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LedgerEncryptionKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LedgerEncryptionKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ledgerencryptionkey.Table, sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LedgerEncryptionKeyDeleteOne is the builder for deleting a single LedgerEncryptionKey entity.
type LedgerEncryptionKeyDeleteOne struct {
	_d *LedgerEncryptionKeyDelete
}

// Where appends a list predicates to the LedgerEncryptionKeyDelete builder.
func (_d *LedgerEncryptionKeyDeleteOne) Where(ps ...predicate.LedgerEncryptionKey) *LedgerEncryptionKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LedgerEncryptionKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ledgerencryptionkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LedgerEncryptionKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
