// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/journalentry"
	"github.com/suda-3156/kkb/go/ent/ledgeraccount"
	"github.com/suda-3156/kkb/go/ent/ledgerencryptionkey"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/transaction"
)

// LedgerEncryptionKeyUpdate is the builder for updating LedgerEncryptionKey entities.
type LedgerEncryptionKeyUpdate struct {
	config
	hooks    []Hook
	mutation *LedgerEncryptionKeyMutation
}

// Where appends a list predicates to the LedgerEncryptionKeyUpdate builder.
func (_u *LedgerEncryptionKeyUpdate) Where(ps ...predicate.LedgerEncryptionKey) *LedgerEncryptionKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAad sets the "aad" field.
func (_u *LedgerEncryptionKeyUpdate) SetAad(v []byte) *LedgerEncryptionKeyUpdate {
	_u.mutation.SetAad(v)
	return _u
}

// SetWrappedCipher sets the "wrapped_cipher" field.
func (_u *LedgerEncryptionKeyUpdate) SetWrappedCipher(v []byte) *LedgerEncryptionKeyUpdate {
	_u.mutation.SetWrappedCipher(v)
	return _u
}

// SetAllowed sets the "allowed" field.
func (_u *LedgerEncryptionKeyUpdate) SetAllowed(v bool) *LedgerEncryptionKeyUpdate {
	_u.mutation.SetAllowed(v)
	return _u
}

// SetNillableAllowed sets the "allowed" field if the given value is not nil.
func (_u *LedgerEncryptionKeyUpdate) SetNillableAllowed(v *bool) *LedgerEncryptionKeyUpdate {
	if v != nil {
		_u.SetAllowed(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LedgerEncryptionKeyUpdate) SetUpdatedAt(v time.Time) *LedgerEncryptionKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLedgerAccountIDs adds the "ledger_accounts" edge to the LedgerAccount entity by IDs.
func (_u *LedgerEncryptionKeyUpdate) AddLedgerAccountIDs(ids ...int) *LedgerEncryptionKeyUpdate {
	_u.mutation.AddLedgerAccountIDs(ids...)
	return _u
}

// AddLedgerAccounts adds the "ledger_accounts" edges to the LedgerAccount entity.
func (_u *LedgerEncryptionKeyUpdate) AddLedgerAccounts(v ...*LedgerAccount) *LedgerEncryptionKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerAccountIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *LedgerEncryptionKeyUpdate) AddTransactionIDs(ids ...int) *LedgerEncryptionKeyUpdate {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *LedgerEncryptionKeyUpdate) AddTransactions(v ...*Transaction) *LedgerEncryptionKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddJournalEntryIDs adds the "journal_entries" edge to the JournalEntry entity by IDs.
func (_u *LedgerEncryptionKeyUpdate) AddJournalEntryIDs(ids ...int) *LedgerEncryptionKeyUpdate {
	_u.mutation.AddJournalEntryIDs(ids...)
	return _u
}

// AddJournalEntries adds the "journal_entries" edges to the JournalEntry entity.
func (_u *LedgerEncryptionKeyUpdate) AddJournalEntries(v ...*JournalEntry) *LedgerEncryptionKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJournalEntryIDs(ids...)
}

// Mutation returns the LedgerEncryptionKeyMutation object of the builder.
func (_u *LedgerEncryptionKeyUpdate) Mutation() *LedgerEncryptionKeyMutation {
	return _u.mutation
}

// ClearLedgerAccounts clears all "ledger_accounts" edges to the LedgerAccount entity.
func (_u *LedgerEncryptionKeyUpdate) ClearLedgerAccounts() *LedgerEncryptionKeyUpdate {
	_u.mutation.ClearLedgerAccounts()
	return _u
}

// RemoveLedgerAccountIDs removes the "ledger_accounts" edge to LedgerAccount entities by IDs.
func (_u *LedgerEncryptionKeyUpdate) RemoveLedgerAccountIDs(ids ...int) *LedgerEncryptionKeyUpdate {
	_u.mutation.RemoveLedgerAccountIDs(ids...)
	return _u
}

// RemoveLedgerAccounts removes "ledger_accounts" edges to LedgerAccount entities.
func (_u *LedgerEncryptionKeyUpdate) RemoveLedgerAccounts(v ...*LedgerAccount) *LedgerEncryptionKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerAccountIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *LedgerEncryptionKeyUpdate) ClearTransactions() *LedgerEncryptionKeyUpdate {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *LedgerEncryptionKeyUpdate) RemoveTransactionIDs(ids ...int) *LedgerEncryptionKeyUpdate {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *LedgerEncryptionKeyUpdate) RemoveTransactions(v ...*Transaction) *LedgerEncryptionKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearJournalEntries clears all "journal_entries" edges to the JournalEntry entity.
func (_u *LedgerEncryptionKeyUpdate) ClearJournalEntries() *LedgerEncryptionKeyUpdate {
	_u.mutation.ClearJournalEntries()
	return _u
}

// RemoveJournalEntryIDs removes the "journal_entries" edge to JournalEntry entities by IDs.
func (_u *LedgerEncryptionKeyUpdate) RemoveJournalEntryIDs(ids ...int) *LedgerEncryptionKeyUpdate {
	_u.mutation.RemoveJournalEntryIDs(ids...)
	return _u
}

// RemoveJournalEntries removes "journal_entries" edges to JournalEntry entities.
func (_u *LedgerEncryptionKeyUpdate) RemoveJournalEntries(v ...*JournalEntry) *LedgerEncryptionKeyUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJournalEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LedgerEncryptionKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerEncryptionKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LedgerEncryptionKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerEncryptionKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LedgerEncryptionKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ledgerencryptionkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerEncryptionKeyUpdate) check() error {
	if v, ok := _u.mutation.Aad(); ok {
		if err := ledgerencryptionkey.AadValidator(v); err != nil {
			return &ValidationError{Name: "aad", err: fmt.Errorf(`ent: validator failed for field "LedgerEncryptionKey.aad": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WrappedCipher(); ok {
		if err := ledgerencryptionkey.WrappedCipherValidator(v); err != nil {
			return &ValidationError{Name: "wrapped_cipher", err: fmt.Errorf(`ent: validator failed for field "LedgerEncryptionKey.wrapped_cipher": %w`, err)}
		}
	}
	return nil
}

func (_u *LedgerEncryptionKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgerencryptionkey.Table, ledgerencryptionkey.Columns, sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Aad(); ok {
		_spec.SetField(ledgerencryptionkey.FieldAad, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.WrappedCipher(); ok {
		_spec.SetField(ledgerencryptionkey.FieldWrappedCipher, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Allowed(); ok {
		_spec.SetField(ledgerencryptionkey.FieldAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ledgerencryptionkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LedgerAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.LedgerAccountsTable,
			Columns: []string{ledgerencryptionkey.LedgerAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgerAccountsIDs(); len(nodes) > 0 && !_u.mutation.LedgerAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.LedgerAccountsTable,
			Columns: []string{ledgerencryptionkey.LedgerAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.LedgerAccountsTable,
			Columns: []string{ledgerencryptionkey.LedgerAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.TransactionsTable,
			Columns: []string{ledgerencryptionkey.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.TransactionsTable,
			Columns: []string{ledgerencryptionkey.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.TransactionsTable,
			Columns: []string{ledgerencryptionkey.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JournalEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.JournalEntriesTable,
			Columns: []string{ledgerencryptionkey.JournalEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJournalEntriesIDs(); len(nodes) > 0 && !_u.mutation.JournalEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.JournalEntriesTable,
			Columns: []string{ledgerencryptionkey.JournalEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JournalEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.JournalEntriesTable,
			Columns: []string{ledgerencryptionkey.JournalEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgerencryptionkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LedgerEncryptionKeyUpdateOne is the builder for updating a single LedgerEncryptionKey entity.
type LedgerEncryptionKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LedgerEncryptionKeyMutation
}

// SetAad sets the "aad" field.
func (_u *LedgerEncryptionKeyUpdateOne) SetAad(v []byte) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.SetAad(v)
	return _u
}

// SetWrappedCipher sets the "wrapped_cipher" field.
func (_u *LedgerEncryptionKeyUpdateOne) SetWrappedCipher(v []byte) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.SetWrappedCipher(v)
	return _u
}

// SetAllowed sets the "allowed" field.
func (_u *LedgerEncryptionKeyUpdateOne) SetAllowed(v bool) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.SetAllowed(v)
	return _u
}

// SetNillableAllowed sets the "allowed" field if the given value is not nil.
func (_u *LedgerEncryptionKeyUpdateOne) SetNillableAllowed(v *bool) *LedgerEncryptionKeyUpdateOne {
	if v != nil {
		_u.SetAllowed(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LedgerEncryptionKeyUpdateOne) SetUpdatedAt(v time.Time) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLedgerAccountIDs adds the "ledger_accounts" edge to the LedgerAccount entity by IDs.
func (_u *LedgerEncryptionKeyUpdateOne) AddLedgerAccountIDs(ids ...int) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.AddLedgerAccountIDs(ids...)
	return _u
}

// AddLedgerAccounts adds the "ledger_accounts" edges to the LedgerAccount entity.
func (_u *LedgerEncryptionKeyUpdateOne) AddLedgerAccounts(v ...*LedgerAccount) *LedgerEncryptionKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLedgerAccountIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *LedgerEncryptionKeyUpdateOne) AddTransactionIDs(ids ...int) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *LedgerEncryptionKeyUpdateOne) AddTransactions(v ...*Transaction) *LedgerEncryptionKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddJournalEntryIDs adds the "journal_entries" edge to the JournalEntry entity by IDs.
func (_u *LedgerEncryptionKeyUpdateOne) AddJournalEntryIDs(ids ...int) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.AddJournalEntryIDs(ids...)
	return _u
}

// AddJournalEntries adds the "journal_entries" edges to the JournalEntry entity.
func (_u *LedgerEncryptionKeyUpdateOne) AddJournalEntries(v ...*JournalEntry) *LedgerEncryptionKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddJournalEntryIDs(ids...)
}

// Mutation returns the LedgerEncryptionKeyMutation object of the builder.
func (_u *LedgerEncryptionKeyUpdateOne) Mutation() *LedgerEncryptionKeyMutation {
	return _u.mutation
}

// ClearLedgerAccounts clears all "ledger_accounts" edges to the LedgerAccount entity.
func (_u *LedgerEncryptionKeyUpdateOne) ClearLedgerAccounts() *LedgerEncryptionKeyUpdateOne {
	_u.mutation.ClearLedgerAccounts()
	return _u
}

// RemoveLedgerAccountIDs removes the "ledger_accounts" edge to LedgerAccount entities by IDs.
func (_u *LedgerEncryptionKeyUpdateOne) RemoveLedgerAccountIDs(ids ...int) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.RemoveLedgerAccountIDs(ids...)
	return _u
}

// RemoveLedgerAccounts removes "ledger_accounts" edges to LedgerAccount entities.
func (_u *LedgerEncryptionKeyUpdateOne) RemoveLedgerAccounts(v ...*LedgerAccount) *LedgerEncryptionKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLedgerAccountIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *LedgerEncryptionKeyUpdateOne) ClearTransactions() *LedgerEncryptionKeyUpdateOne {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *LedgerEncryptionKeyUpdateOne) RemoveTransactionIDs(ids ...int) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *LedgerEncryptionKeyUpdateOne) RemoveTransactions(v ...*Transaction) *LedgerEncryptionKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearJournalEntries clears all "journal_entries" edges to the JournalEntry entity.
func (_u *LedgerEncryptionKeyUpdateOne) ClearJournalEntries() *LedgerEncryptionKeyUpdateOne {
	_u.mutation.ClearJournalEntries()
	return _u
}

// RemoveJournalEntryIDs removes the "journal_entries" edge to JournalEntry entities by IDs.
func (_u *LedgerEncryptionKeyUpdateOne) RemoveJournalEntryIDs(ids ...int) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.RemoveJournalEntryIDs(ids...)
	return _u
}

// RemoveJournalEntries removes "journal_entries" edges to JournalEntry entities.
func (_u *LedgerEncryptionKeyUpdateOne) RemoveJournalEntries(v ...*JournalEntry) *LedgerEncryptionKeyUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveJournalEntryIDs(ids...)
}

// Where appends a list predicates to the LedgerEncryptionKeyUpdate builder.
func (_u *LedgerEncryptionKeyUpdateOne) Where(ps ...predicate.LedgerEncryptionKey) *LedgerEncryptionKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LedgerEncryptionKeyUpdateOne) Select(field string, fields ...string) *LedgerEncryptionKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LedgerEncryptionKey entity.
func (_u *LedgerEncryptionKeyUpdateOne) Save(ctx context.Context) (*LedgerEncryptionKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LedgerEncryptionKeyUpdateOne) SaveX(ctx context.Context) *LedgerEncryptionKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LedgerEncryptionKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LedgerEncryptionKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LedgerEncryptionKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ledgerencryptionkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LedgerEncryptionKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Aad(); ok {
		if err := ledgerencryptionkey.AadValidator(v); err != nil {
			return &ValidationError{Name: "aad", err: fmt.Errorf(`ent: validator failed for field "LedgerEncryptionKey.aad": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WrappedCipher(); ok {
		if err := ledgerencryptionkey.WrappedCipherValidator(v); err != nil {
			return &ValidationError{Name: "wrapped_cipher", err: fmt.Errorf(`ent: validator failed for field "LedgerEncryptionKey.wrapped_cipher": %w`, err)}
		}
	}
	return nil
}

func (_u *LedgerEncryptionKeyUpdateOne) sqlSave(ctx context.Context) (_node *LedgerEncryptionKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ledgerencryptionkey.Table, ledgerencryptionkey.Columns, sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LedgerEncryptionKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ledgerencryptionkey.FieldID)
		for _, f := range fields {
			if !ledgerencryptionkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ledgerencryptionkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Aad(); ok {
		_spec.SetField(ledgerencryptionkey.FieldAad, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.WrappedCipher(); ok {
		_spec.SetField(ledgerencryptionkey.FieldWrappedCipher, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Allowed(); ok {
		_spec.SetField(ledgerencryptionkey.FieldAllowed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ledgerencryptionkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LedgerAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.LedgerAccountsTable,
			Columns: []string{ledgerencryptionkey.LedgerAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLedgerAccountsIDs(); len(nodes) > 0 && !_u.mutation.LedgerAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.LedgerAccountsTable,
			Columns: []string{ledgerencryptionkey.LedgerAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LedgerAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.LedgerAccountsTable,
			Columns: []string{ledgerencryptionkey.LedgerAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.TransactionsTable,
			Columns: []string{ledgerencryptionkey.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.TransactionsTable,
			Columns: []string{ledgerencryptionkey.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.TransactionsTable,
			Columns: []string{ledgerencryptionkey.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.JournalEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.JournalEntriesTable,
			Columns: []string{ledgerencryptionkey.JournalEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedJournalEntriesIDs(); len(nodes) > 0 && !_u.mutation.JournalEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.JournalEntriesTable,
			Columns: []string{ledgerencryptionkey.JournalEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JournalEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgerencryptionkey.JournalEntriesTable,
			Columns: []string{ledgerencryptionkey.JournalEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LedgerEncryptionKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ledgerencryptionkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
