// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/ledgeraccount"
	"github.com/suda-3156/kkb/go/pkg/pulid"
)

// LedgerAccountCreate is the builder for creating a LedgerAccount entity.
type LedgerAccountCreate struct {
	config
	mutation *LedgerAccountMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (_c *LedgerAccountCreate) SetPublicID(v pulid.ID) *LedgerAccountCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetAccountName sets the "account_name" field.
func (_c *LedgerAccountCreate) SetAccountName(v []byte) *LedgerAccountCreate {
	_c.mutation.SetAccountName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *LedgerAccountCreate) SetKind(v int) *LedgerAccountCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetIsGroup sets the "is_group" field.
func (_c *LedgerAccountCreate) SetIsGroup(v bool) *LedgerAccountCreate {
	_c.mutation.SetIsGroup(v)
	return _c
}

// SetArchivedAt sets the "archived_at" field.
func (_c *LedgerAccountCreate) SetArchivedAt(v []byte) *LedgerAccountCreate {
	_c.mutation.SetArchivedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LedgerAccountCreate) SetCreatedAt(v time.Time) *LedgerAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LedgerAccountCreate) SetNillableCreatedAt(v *time.Time) *LedgerAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LedgerAccountCreate) SetUpdatedAt(v time.Time) *LedgerAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LedgerAccountCreate) SetNillableUpdatedAt(v *time.Time) *LedgerAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetParentID sets the "parent" edge to the LedgerAccount entity by ID.
func (_c *LedgerAccountCreate) SetParentID(id int) *LedgerAccountCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the LedgerAccount entity by ID if the given value is not nil.
func (_c *LedgerAccountCreate) SetNillableParentID(id *int) *LedgerAccountCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the LedgerAccount entity.
func (_c *LedgerAccountCreate) SetParent(v *LedgerAccount) *LedgerAccountCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the LedgerAccount entity by IDs.
func (_c *LedgerAccountCreate) AddChildIDs(ids ...int) *LedgerAccountCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the LedgerAccount entity.
func (_c *LedgerAccountCreate) AddChildren(v ...*LedgerAccount) *LedgerAccountCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// Mutation returns the LedgerAccountMutation object of the builder.
func (_c *LedgerAccountCreate) Mutation() *LedgerAccountMutation {
	return _c.mutation
}

// Save creates the LedgerAccount in the database.
func (_c *LedgerAccountCreate) Save(ctx context.Context) (*LedgerAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LedgerAccountCreate) SaveX(ctx context.Context) *LedgerAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LedgerAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ledgeraccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ledgeraccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LedgerAccountCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "LedgerAccount.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := ledgeraccount.PublicIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "LedgerAccount.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "LedgerAccount.account_name"`)}
	}
	if v, ok := _c.mutation.AccountName(); ok {
		if err := ledgeraccount.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "LedgerAccount.account_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "LedgerAccount.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := ledgeraccount.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "LedgerAccount.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsGroup(); !ok {
		return &ValidationError{Name: "is_group", err: errors.New(`ent: missing required field "LedgerAccount.is_group"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LedgerAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LedgerAccount.updated_at"`)}
	}
	return nil
}

func (_c *LedgerAccountCreate) sqlSave(ctx context.Context) (*LedgerAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LedgerAccountCreate) createSpec() (*LedgerAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &LedgerAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ledgeraccount.Table, sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(ledgeraccount.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.AccountName(); ok {
		_spec.SetField(ledgeraccount.FieldAccountName, field.TypeBytes, value)
		_node.AccountName = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(ledgeraccount.FieldKind, field.TypeInt, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.IsGroup(); ok {
		_spec.SetField(ledgeraccount.FieldIsGroup, field.TypeBool, value)
		_node.IsGroup = value
	}
	if value, ok := _c.mutation.ArchivedAt(); ok {
		_spec.SetField(ledgeraccount.FieldArchivedAt, field.TypeBytes, value)
		_node.ArchivedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ledgeraccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ledgeraccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ledgeraccount.ParentTable,
			Columns: []string{ledgeraccount.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_account_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ledgeraccount.ChildrenTable,
			Columns: []string{ledgeraccount.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LedgerAccountCreateBulk is the builder for creating many LedgerAccount entities in bulk.
type LedgerAccountCreateBulk struct {
	config
	err      error
	builders []*LedgerAccountCreate
}

// Save creates the LedgerAccount entities in the database.
func (_c *LedgerAccountCreateBulk) Save(ctx context.Context) ([]*LedgerAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LedgerAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LedgerAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LedgerAccountCreateBulk) SaveX(ctx context.Context) []*LedgerAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LedgerAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LedgerAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
