// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/ledgeraccount"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/ent/subscriptionentry"
)

// SubscriptionEntryCreate is the builder for creating a SubscriptionEntry entity.
type SubscriptionEntryCreate struct {
	config
	mutation *SubscriptionEntryMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (_c *SubscriptionEntryCreate) SetAmount(v int32) *SubscriptionEntryCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *SubscriptionEntryCreate) SetKind(v schema.JournalEntryKind) *SubscriptionEntryCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (_c *SubscriptionEntryCreate) SetSubscriptionID(id int) *SubscriptionEntryCreate {
	_c.mutation.SetSubscriptionID(id)
	return _c
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_c *SubscriptionEntryCreate) SetSubscription(v *Subscription) *SubscriptionEntryCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetLedgerAccountID sets the "ledger_account" edge to the LedgerAccount entity by ID.
func (_c *SubscriptionEntryCreate) SetLedgerAccountID(id int) *SubscriptionEntryCreate {
	_c.mutation.SetLedgerAccountID(id)
	return _c
}

// SetLedgerAccount sets the "ledger_account" edge to the LedgerAccount entity.
func (_c *SubscriptionEntryCreate) SetLedgerAccount(v *LedgerAccount) *SubscriptionEntryCreate {
	return _c.SetLedgerAccountID(v.ID)
}

// Mutation returns the SubscriptionEntryMutation object of the builder.
func (_c *SubscriptionEntryCreate) Mutation() *SubscriptionEntryMutation {
	return _c.mutation
}

// Save creates the SubscriptionEntry in the database.
func (_c *SubscriptionEntryCreate) Save(ctx context.Context) (*SubscriptionEntry, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionEntryCreate) SaveX(ctx context.Context) *SubscriptionEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionEntryCreate) check() error {
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "SubscriptionEntry.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := subscriptionentry.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntry.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "SubscriptionEntry.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := subscriptionentry.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntry.kind": %w`, err)}
		}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "SubscriptionEntry.subscription"`)}
	}
	if len(_c.mutation.LedgerAccountIDs()) == 0 {
		return &ValidationError{Name: "ledger_account", err: errors.New(`ent: missing required edge "SubscriptionEntry.ledger_account"`)}
	}
	return nil
}

func (_c *SubscriptionEntryCreate) sqlSave(ctx context.Context) (*SubscriptionEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionEntryCreate) createSpec() (*SubscriptionEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionentry.Table, sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(subscriptionentry.FieldAmount, field.TypeInt32, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(subscriptionentry.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentry.SubscriptionTable,
			Columns: []string{subscriptionentry.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.subscription_template_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LedgerAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentry.LedgerAccountTable,
			Columns: []string{subscriptionentry.LedgerAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgeraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_account_subscription_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubscriptionEntryCreateBulk is the builder for creating many SubscriptionEntry entities in bulk.
type SubscriptionEntryCreateBulk struct {
	config
	err      error
	builders []*SubscriptionEntryCreate
}

// Save creates the SubscriptionEntry entities in the database.
func (_c *SubscriptionEntryCreateBulk) Save(ctx context.Context) ([]*SubscriptionEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionEntryCreateBulk) SaveX(ctx context.Context) []*SubscriptionEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
