// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/suda-3156/kkb/go/ent/ledgerencryptionkey"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/internal/date"
	"github.com/suda-3156/kkb/go/internal/prid"
)

// Subscription is the model entity for the Subscription schema.
type Subscription struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID prid.ID `json:"public_id,omitempty"`
	// Name holds the value of the "name" field.
	Name []byte `json:"name,omitempty"`
	// RegisteredOn holds the value of the "registered_on" field.
	RegisteredOn date.Date `json:"registered_on,omitempty"`
	// AnchorOn holds the value of the "anchor_on" field.
	AnchorOn date.Date `json:"anchor_on,omitempty"`
	// NextOccurrenceOn holds the value of the "next_occurrence_on" field.
	NextOccurrenceOn date.Date `json:"next_occurrence_on,omitempty"`
	// CoveredThroughOn holds the value of the "covered_through_on" field.
	CoveredThroughOn date.Date `json:"covered_through_on,omitempty"`
	// IntervalMonths holds the value of the "interval_months" field.
	IntervalMonths int `json:"interval_months,omitempty"`
	// Status holds the value of the "status" field.
	Status schema.SubscriptionStatus `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionQuery when eager-loading is set.
	Edges                               SubscriptionEdges `json:"edges"`
	ledger_encryption_key_subscriptions *int
	selectValues                        sql.SelectValues
}

// SubscriptionEdges holds the relations/edges for other nodes in the graph.
type SubscriptionEdges struct {
	// TemplateEntries holds the value of the template_entries edge.
	TemplateEntries []*SubscriptionEntry `json:"template_entries,omitempty"`
	// Occurrences holds the value of the occurrences edge.
	Occurrences []*SubscriptionOccurrence `json:"occurrences,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*Transaction `json:"transactions,omitempty"`
	// EncryptionKey holds the value of the encryption_key edge.
	EncryptionKey *LedgerEncryptionKey `json:"encryption_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// TemplateEntriesOrErr returns the TemplateEntries value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionEdges) TemplateEntriesOrErr() ([]*SubscriptionEntry, error) {
	if e.loadedTypes[0] {
		return e.TemplateEntries, nil
	}
	return nil, &NotLoadedError{edge: "template_entries"}
}

// OccurrencesOrErr returns the Occurrences value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionEdges) OccurrencesOrErr() ([]*SubscriptionOccurrence, error) {
	if e.loadedTypes[1] {
		return e.Occurrences, nil
	}
	return nil, &NotLoadedError{edge: "occurrences"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionEdges) TransactionsOrErr() ([]*Transaction, error) {
	if e.loadedTypes[2] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// EncryptionKeyOrErr returns the EncryptionKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionEdges) EncryptionKeyOrErr() (*LedgerEncryptionKey, error) {
	if e.EncryptionKey != nil {
		return e.EncryptionKey, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: ledgerencryptionkey.Label}
	}
	return nil, &NotLoadedError{edge: "encryption_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscription.FieldName:
			values[i] = new([]byte)
		case subscription.FieldPublicID:
			values[i] = new(prid.ID)
		case subscription.FieldID, subscription.FieldIntervalMonths:
			values[i] = new(sql.NullInt64)
		case subscription.FieldRegisteredOn, subscription.FieldAnchorOn, subscription.FieldNextOccurrenceOn, subscription.FieldCoveredThroughOn, subscription.FieldStatus:
			values[i] = new(sql.NullString)
		case subscription.FieldCreatedAt, subscription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case subscription.ForeignKeys[0]: // ledger_encryption_key_subscriptions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subscription fields.
func (_m *Subscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscription.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case subscription.FieldPublicID:
			if value, ok := values[i].(*prid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case subscription.FieldName:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value != nil {
				_m.Name = *value
			}
		case subscription.FieldRegisteredOn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field registered_on", values[i])
			} else if value.Valid {
				_m.RegisteredOn = date.Date(value.String)
			}
		case subscription.FieldAnchorOn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field anchor_on", values[i])
			} else if value.Valid {
				_m.AnchorOn = date.Date(value.String)
			}
		case subscription.FieldNextOccurrenceOn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field next_occurrence_on", values[i])
			} else if value.Valid {
				_m.NextOccurrenceOn = date.Date(value.String)
			}
		case subscription.FieldCoveredThroughOn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field covered_through_on", values[i])
			} else if value.Valid {
				_m.CoveredThroughOn = date.Date(value.String)
			}
		case subscription.FieldIntervalMonths:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_months", values[i])
			} else if value.Valid {
				_m.IntervalMonths = int(value.Int64)
			}
		case subscription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = schema.SubscriptionStatus(value.String)
			}
		case subscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscription.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ledger_encryption_key_subscriptions", value)
			} else if value.Valid {
				_m.ledger_encryption_key_subscriptions = new(int)
				*_m.ledger_encryption_key_subscriptions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Subscription.
// This includes values selected through modifiers, order, etc.
func (_m *Subscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTemplateEntries queries the "template_entries" edge of the Subscription entity.
func (_m *Subscription) QueryTemplateEntries() *SubscriptionEntryQuery {
	return NewSubscriptionClient(_m.config).QueryTemplateEntries(_m)
}

// QueryOccurrences queries the "occurrences" edge of the Subscription entity.
func (_m *Subscription) QueryOccurrences() *SubscriptionOccurrenceQuery {
	return NewSubscriptionClient(_m.config).QueryOccurrences(_m)
}

// QueryTransactions queries the "transactions" edge of the Subscription entity.
func (_m *Subscription) QueryTransactions() *TransactionQuery {
	return NewSubscriptionClient(_m.config).QueryTransactions(_m)
}

// QueryEncryptionKey queries the "encryption_key" edge of the Subscription entity.
func (_m *Subscription) QueryEncryptionKey() *LedgerEncryptionKeyQuery {
	return NewSubscriptionClient(_m.config).QueryEncryptionKey(_m)
}

// Update returns a builder for updating this Subscription.
// Note that you need to call Subscription.Unwrap() before calling this method if this Subscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Subscription) Update() *SubscriptionUpdateOne {
	return NewSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Subscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Subscription) Unwrap() *Subscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Subscription) String() string {
	var builder strings.Builder
	builder.WriteString("Subscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(fmt.Sprintf("%v", _m.Name))
	builder.WriteString(", ")
	builder.WriteString("registered_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.RegisteredOn))
	builder.WriteString(", ")
	builder.WriteString("anchor_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnchorOn))
	builder.WriteString(", ")
	builder.WriteString("next_occurrence_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextOccurrenceOn))
	builder.WriteString(", ")
	builder.WriteString("covered_through_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.CoveredThroughOn))
	builder.WriteString(", ")
	builder.WriteString("interval_months=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalMonths))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Subscriptions is a parsable slice of Subscription.
type Subscriptions []*Subscription
