// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/ent/subscriptionoccurrence"
	"github.com/suda-3156/kkb/go/internal/date"
)

// SubscriptionOccurrenceUpdate is the builder for updating SubscriptionOccurrence entities.
type SubscriptionOccurrenceUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionOccurrenceMutation
}

// Where appends a list predicates to the SubscriptionOccurrenceUpdate builder.
func (_u *SubscriptionOccurrenceUpdate) Where(ps ...predicate.SubscriptionOccurrence) *SubscriptionOccurrenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOccurrenceOn sets the "occurrence_on" field.
func (_u *SubscriptionOccurrenceUpdate) SetOccurrenceOn(v date.Date) *SubscriptionOccurrenceUpdate {
	_u.mutation.SetOccurrenceOn(v)
	return _u
}

// SetNillableOccurrenceOn sets the "occurrence_on" field if the given value is not nil.
func (_u *SubscriptionOccurrenceUpdate) SetNillableOccurrenceOn(v *date.Date) *SubscriptionOccurrenceUpdate {
	if v != nil {
		_u.SetOccurrenceOn(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *SubscriptionOccurrenceUpdate) SetOutcome(v schema.OccurrenceOutcome) *SubscriptionOccurrenceUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *SubscriptionOccurrenceUpdate) SetNillableOutcome(v *schema.OccurrenceOutcome) *SubscriptionOccurrenceUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (_u *SubscriptionOccurrenceUpdate) SetSubscriptionID(id int) *SubscriptionOccurrenceUpdate {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *SubscriptionOccurrenceUpdate) SetSubscription(v *Subscription) *SubscriptionOccurrenceUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionOccurrenceMutation object of the builder.
func (_u *SubscriptionOccurrenceUpdate) Mutation() *SubscriptionOccurrenceMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *SubscriptionOccurrenceUpdate) ClearSubscription() *SubscriptionOccurrenceUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionOccurrenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOccurrenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionOccurrenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOccurrenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOccurrenceUpdate) check() error {
	if v, ok := _u.mutation.OccurrenceOn(); ok {
		if err := subscriptionoccurrence.OccurrenceOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "occurrence_on", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOccurrence.occurrence_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := subscriptionoccurrence.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOccurrence.outcome": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOccurrence.subscription"`)
	}
	return nil
}

func (_u *SubscriptionOccurrenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionoccurrence.Table, subscriptionoccurrence.Columns, sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OccurrenceOn(); ok {
		_spec.SetField(subscriptionoccurrence.FieldOccurrenceOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(subscriptionoccurrence.FieldOutcome, field.TypeEnum, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoccurrence.SubscriptionTable,
			Columns: []string{subscriptionoccurrence.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoccurrence.SubscriptionTable,
			Columns: []string{subscriptionoccurrence.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionoccurrence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionOccurrenceUpdateOne is the builder for updating a single SubscriptionOccurrence entity.
type SubscriptionOccurrenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionOccurrenceMutation
}

// SetOccurrenceOn sets the "occurrence_on" field.
func (_u *SubscriptionOccurrenceUpdateOne) SetOccurrenceOn(v date.Date) *SubscriptionOccurrenceUpdateOne {
	_u.mutation.SetOccurrenceOn(v)
	return _u
}

// SetNillableOccurrenceOn sets the "occurrence_on" field if the given value is not nil.
func (_u *SubscriptionOccurrenceUpdateOne) SetNillableOccurrenceOn(v *date.Date) *SubscriptionOccurrenceUpdateOne {
	if v != nil {
		_u.SetOccurrenceOn(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *SubscriptionOccurrenceUpdateOne) SetOutcome(v schema.OccurrenceOutcome) *SubscriptionOccurrenceUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *SubscriptionOccurrenceUpdateOne) SetNillableOutcome(v *schema.OccurrenceOutcome) *SubscriptionOccurrenceUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the Subscription entity by ID.
func (_u *SubscriptionOccurrenceUpdateOne) SetSubscriptionID(id int) *SubscriptionOccurrenceUpdateOne {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *SubscriptionOccurrenceUpdateOne) SetSubscription(v *Subscription) *SubscriptionOccurrenceUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionOccurrenceMutation object of the builder.
func (_u *SubscriptionOccurrenceUpdateOne) Mutation() *SubscriptionOccurrenceMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *SubscriptionOccurrenceUpdateOne) ClearSubscription() *SubscriptionOccurrenceUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the SubscriptionOccurrenceUpdate builder.
func (_u *SubscriptionOccurrenceUpdateOne) Where(ps ...predicate.SubscriptionOccurrence) *SubscriptionOccurrenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionOccurrenceUpdateOne) Select(field string, fields ...string) *SubscriptionOccurrenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionOccurrence entity.
func (_u *SubscriptionOccurrenceUpdateOne) Save(ctx context.Context) (*SubscriptionOccurrence, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOccurrenceUpdateOne) SaveX(ctx context.Context) *SubscriptionOccurrence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionOccurrenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOccurrenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOccurrenceUpdateOne) check() error {
	if v, ok := _u.mutation.OccurrenceOn(); ok {
		if err := subscriptionoccurrence.OccurrenceOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "occurrence_on", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOccurrence.occurrence_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := subscriptionoccurrence.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "SubscriptionOccurrence.outcome": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOccurrence.subscription"`)
	}
	return nil
}

func (_u *SubscriptionOccurrenceUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionOccurrence, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionoccurrence.Table, subscriptionoccurrence.Columns, sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionOccurrence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionoccurrence.FieldID)
		for _, f := range fields {
			if !subscriptionoccurrence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionoccurrence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OccurrenceOn(); ok {
		_spec.SetField(subscriptionoccurrence.FieldOccurrenceOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(subscriptionoccurrence.FieldOutcome, field.TypeEnum, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoccurrence.SubscriptionTable,
			Columns: []string{subscriptionoccurrence.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoccurrence.SubscriptionTable,
			Columns: []string{subscriptionoccurrence.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionOccurrence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionoccurrence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
