// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/ent/subscriptionoccurrence"
)

// SubscriptionOccurrenceQuery is the builder for querying SubscriptionOccurrence entities.
type SubscriptionOccurrenceQuery struct {
	config
	ctx              *QueryContext
	order            []subscriptionoccurrence.OrderOption
	inters           []Interceptor
	predicates       []predicate.SubscriptionOccurrence
	withSubscription *SubscriptionQuery
	withFKs          bool
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionOccurrenceQuery builder.
func (_q *SubscriptionOccurrenceQuery) Where(ps ...predicate.SubscriptionOccurrence) *SubscriptionOccurrenceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubscriptionOccurrenceQuery) Limit(limit int) *SubscriptionOccurrenceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubscriptionOccurrenceQuery) Offset(offset int) *SubscriptionOccurrenceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubscriptionOccurrenceQuery) Unique(unique bool) *SubscriptionOccurrenceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubscriptionOccurrenceQuery) Order(o ...subscriptionoccurrence.OrderOption) *SubscriptionOccurrenceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySubscription chains the current query on the "subscription" edge.
func (_q *SubscriptionOccurrenceQuery) QuerySubscription() *SubscriptionQuery {
	query := (&SubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionoccurrence.Table, subscriptionoccurrence.FieldID, selector),
			sqlgraph.To(subscription.Table, subscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionoccurrence.SubscriptionTable, subscriptionoccurrence.SubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubscriptionOccurrence entity from the query.
// Returns a *NotFoundError when no SubscriptionOccurrence was found.
func (_q *SubscriptionOccurrenceQuery) First(ctx context.Context) (*SubscriptionOccurrence, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionoccurrence.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) FirstX(ctx context.Context) *SubscriptionOccurrence {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionOccurrence ID from the query.
// Returns a *NotFoundError when no SubscriptionOccurrence ID was found.
func (_q *SubscriptionOccurrenceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionoccurrence.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionOccurrence entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionOccurrence entity is found.
// Returns a *NotFoundError when no SubscriptionOccurrence entities are found.
func (_q *SubscriptionOccurrenceQuery) Only(ctx context.Context) (*SubscriptionOccurrence, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionoccurrence.Label}
	default:
		return nil, &NotSingularError{subscriptionoccurrence.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) OnlyX(ctx context.Context) *SubscriptionOccurrence {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionOccurrence ID in the query.
// Returns a *NotSingularError when more than one SubscriptionOccurrence ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubscriptionOccurrenceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionoccurrence.Label}
	default:
		err = &NotSingularError{subscriptionoccurrence.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionOccurrences.
func (_q *SubscriptionOccurrenceQuery) All(ctx context.Context) ([]*SubscriptionOccurrence, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionOccurrence, *SubscriptionOccurrenceQuery]()
	return withInterceptors[[]*SubscriptionOccurrence](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) AllX(ctx context.Context) []*SubscriptionOccurrence {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionOccurrence IDs.
func (_q *SubscriptionOccurrenceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subscriptionoccurrence.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubscriptionOccurrenceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubscriptionOccurrenceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubscriptionOccurrenceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubscriptionOccurrenceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionOccurrenceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubscriptionOccurrenceQuery) Clone() *SubscriptionOccurrenceQuery {
	if _q == nil {
		return nil
	}
	return &SubscriptionOccurrenceQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]subscriptionoccurrence.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.SubscriptionOccurrence{}, _q.predicates...),
		withSubscription: _q.withSubscription.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSubscription tells the query-builder to eager-load the nodes that are connected to
// the "subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionOccurrenceQuery) WithSubscription(opts ...func(*SubscriptionQuery)) *SubscriptionOccurrenceQuery {
	query := (&SubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubscription = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OccurrenceOn date.Date `json:"occurrence_on,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionOccurrence.Query().
//		GroupBy(subscriptionoccurrence.FieldOccurrenceOn).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubscriptionOccurrenceQuery) GroupBy(field string, fields ...string) *SubscriptionOccurrenceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionOccurrenceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subscriptionoccurrence.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OccurrenceOn date.Date `json:"occurrence_on,omitempty"`
//	}
//
//	client.SubscriptionOccurrence.Query().
//		Select(subscriptionoccurrence.FieldOccurrenceOn).
//		Scan(ctx, &v)
func (_q *SubscriptionOccurrenceQuery) Select(fields ...string) *SubscriptionOccurrenceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubscriptionOccurrenceSelect{SubscriptionOccurrenceQuery: _q}
	sbuild.label = subscriptionoccurrence.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionOccurrenceSelect configured with the given aggregations.
func (_q *SubscriptionOccurrenceQuery) Aggregate(fns ...AggregateFunc) *SubscriptionOccurrenceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubscriptionOccurrenceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subscriptionoccurrence.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubscriptionOccurrenceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionOccurrence, error) {
	var (
		nodes       = []*SubscriptionOccurrence{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSubscription != nil,
		}
	)
	if _q.withSubscription != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionoccurrence.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionOccurrence).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionOccurrence{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSubscription; query != nil {
		if err := _q.loadSubscription(ctx, query, nodes, nil,
			func(n *SubscriptionOccurrence, e *Subscription) { n.Edges.Subscription = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubscriptionOccurrenceQuery) loadSubscription(ctx context.Context, query *SubscriptionQuery, nodes []*SubscriptionOccurrence, init func(*SubscriptionOccurrence), assign func(*SubscriptionOccurrence, *Subscription)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SubscriptionOccurrence)
	for i := range nodes {
		if nodes[i].subscription_occurrences == nil {
			continue
		}
		fk := *nodes[i].subscription_occurrences
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subscription_occurrences" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SubscriptionOccurrenceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubscriptionOccurrenceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionoccurrence.Table, subscriptionoccurrence.Columns, sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionoccurrence.FieldID)
		for i := range fields {
			if fields[i] != subscriptionoccurrence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubscriptionOccurrenceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subscriptionoccurrence.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionoccurrence.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubscriptionOccurrenceQuery) ForUpdate(opts ...sql.LockOption) *SubscriptionOccurrenceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubscriptionOccurrenceQuery) ForShare(opts ...sql.LockOption) *SubscriptionOccurrenceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubscriptionOccurrenceGroupBy is the group-by builder for SubscriptionOccurrence entities.
type SubscriptionOccurrenceGroupBy struct {
	selector
	build *SubscriptionOccurrenceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubscriptionOccurrenceGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionOccurrenceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubscriptionOccurrenceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionOccurrenceQuery, *SubscriptionOccurrenceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubscriptionOccurrenceGroupBy) sqlScan(ctx context.Context, root *SubscriptionOccurrenceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionOccurrenceSelect is the builder for selecting fields of SubscriptionOccurrence entities.
type SubscriptionOccurrenceSelect struct {
	*SubscriptionOccurrenceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubscriptionOccurrenceSelect) Aggregate(fns ...AggregateFunc) *SubscriptionOccurrenceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubscriptionOccurrenceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionOccurrenceQuery, *SubscriptionOccurrenceSelect](ctx, _s.SubscriptionOccurrenceQuery, _s, _s.inters, v)
}

func (_s *SubscriptionOccurrenceSelect) sqlScan(ctx context.Context, root *SubscriptionOccurrenceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
