// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/ledgerencryptionkey"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/ent/subscriptionentry"
	"github.com/suda-3156/kkb/go/ent/subscriptionoccurrence"
	"github.com/suda-3156/kkb/go/ent/transaction"
	"github.com/suda-3156/kkb/go/internal/date"
	"github.com/suda-3156/kkb/go/internal/prid"
)

// SubscriptionCreate is the builder for creating a Subscription entity.
type SubscriptionCreate struct {
	config
	mutation *SubscriptionMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (_c *SubscriptionCreate) SetPublicID(v prid.ID) *SubscriptionCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SubscriptionCreate) SetName(v []byte) *SubscriptionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRegisteredOn sets the "registered_on" field.
func (_c *SubscriptionCreate) SetRegisteredOn(v date.Date) *SubscriptionCreate {
	_c.mutation.SetRegisteredOn(v)
	return _c
}

// SetAnchorOn sets the "anchor_on" field.
func (_c *SubscriptionCreate) SetAnchorOn(v date.Date) *SubscriptionCreate {
	_c.mutation.SetAnchorOn(v)
	return _c
}

// SetNextOccurrenceOn sets the "next_occurrence_on" field.
func (_c *SubscriptionCreate) SetNextOccurrenceOn(v date.Date) *SubscriptionCreate {
	_c.mutation.SetNextOccurrenceOn(v)
	return _c
}

// SetCoveredThroughOn sets the "covered_through_on" field.
func (_c *SubscriptionCreate) SetCoveredThroughOn(v date.Date) *SubscriptionCreate {
	_c.mutation.SetCoveredThroughOn(v)
	return _c
}

// SetIntervalMonths sets the "interval_months" field.
func (_c *SubscriptionCreate) SetIntervalMonths(v int) *SubscriptionCreate {
	_c.mutation.SetIntervalMonths(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionCreate) SetStatus(v schema.SubscriptionStatus) *SubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableStatus(v *schema.SubscriptionStatus) *SubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetColor sets the "color" field.
func (_c *SubscriptionCreate) SetColor(v string) *SubscriptionCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableColor(v *string) *SubscriptionCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionCreate) SetCreatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionCreate) SetUpdatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddTemplateEntryIDs adds the "template_entries" edge to the SubscriptionEntry entity by IDs.
func (_c *SubscriptionCreate) AddTemplateEntryIDs(ids ...int) *SubscriptionCreate {
	_c.mutation.AddTemplateEntryIDs(ids...)
	return _c
}

// AddTemplateEntries adds the "template_entries" edges to the SubscriptionEntry entity.
func (_c *SubscriptionCreate) AddTemplateEntries(v ...*SubscriptionEntry) *SubscriptionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTemplateEntryIDs(ids...)
}

// AddOccurrenceIDs adds the "occurrences" edge to the SubscriptionOccurrence entity by IDs.
func (_c *SubscriptionCreate) AddOccurrenceIDs(ids ...int) *SubscriptionCreate {
	_c.mutation.AddOccurrenceIDs(ids...)
	return _c
}

// AddOccurrences adds the "occurrences" edges to the SubscriptionOccurrence entity.
func (_c *SubscriptionCreate) AddOccurrences(v ...*SubscriptionOccurrence) *SubscriptionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOccurrenceIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_c *SubscriptionCreate) AddTransactionIDs(ids ...int) *SubscriptionCreate {
	_c.mutation.AddTransactionIDs(ids...)
	return _c
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_c *SubscriptionCreate) AddTransactions(v ...*Transaction) *SubscriptionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTransactionIDs(ids...)
}

// SetEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID.
func (_c *SubscriptionCreate) SetEncryptionKeyID(id int) *SubscriptionCreate {
	_c.mutation.SetEncryptionKeyID(id)
	return _c
}

// SetNillableEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableEncryptionKeyID(id *int) *SubscriptionCreate {
	if id != nil {
		_c = _c.SetEncryptionKeyID(*id)
	}
	return _c
}

// SetEncryptionKey sets the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_c *SubscriptionCreate) SetEncryptionKey(v *LedgerEncryptionKey) *SubscriptionCreate {
	return _c.SetEncryptionKeyID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_c *SubscriptionCreate) Mutation() *SubscriptionMutation {
	return _c.mutation
}

// Save creates the Subscription in the database.
func (_c *SubscriptionCreate) Save(ctx context.Context) (*Subscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionCreate) SaveX(ctx context.Context) *Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := subscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "Subscription.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := subscription.PublicIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.public_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Subscription.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := subscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subscription.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RegisteredOn(); !ok {
		return &ValidationError{Name: "registered_on", err: errors.New(`ent: missing required field "Subscription.registered_on"`)}
	}
	if v, ok := _c.mutation.RegisteredOn(); ok {
		if err := subscription.RegisteredOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "registered_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.registered_on": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AnchorOn(); !ok {
		return &ValidationError{Name: "anchor_on", err: errors.New(`ent: missing required field "Subscription.anchor_on"`)}
	}
	if v, ok := _c.mutation.AnchorOn(); ok {
		if err := subscription.AnchorOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "anchor_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.anchor_on": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NextOccurrenceOn(); !ok {
		return &ValidationError{Name: "next_occurrence_on", err: errors.New(`ent: missing required field "Subscription.next_occurrence_on"`)}
	}
	if v, ok := _c.mutation.NextOccurrenceOn(); ok {
		if err := subscription.NextOccurrenceOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "next_occurrence_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.next_occurrence_on": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CoveredThroughOn(); !ok {
		return &ValidationError{Name: "covered_through_on", err: errors.New(`ent: missing required field "Subscription.covered_through_on"`)}
	}
	if v, ok := _c.mutation.CoveredThroughOn(); ok {
		if err := subscription.CoveredThroughOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "covered_through_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.covered_through_on": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntervalMonths(); !ok {
		return &ValidationError{Name: "interval_months", err: errors.New(`ent: missing required field "Subscription.interval_months"`)}
	}
	if v, ok := _c.mutation.IntervalMonths(); ok {
		if err := subscription.IntervalMonthsValidator(v); err != nil {
			return &ValidationError{Name: "interval_months", err: fmt.Errorf(`ent: validator failed for field "Subscription.interval_months": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Subscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Color(); ok {
		if err := subscription.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Subscription.color": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Subscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Subscription.updated_at"`)}
	}
	return nil
}

func (_c *SubscriptionCreate) sqlSave(ctx context.Context) (*Subscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionCreate) createSpec() (*Subscription, *sqlgraph.CreateSpec) {
	var (
		_node = &Subscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscription.Table, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(subscription.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subscription.FieldName, field.TypeBytes, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RegisteredOn(); ok {
		_spec.SetField(subscription.FieldRegisteredOn, field.TypeString, value)
		_node.RegisteredOn = value
	}
	if value, ok := _c.mutation.AnchorOn(); ok {
		_spec.SetField(subscription.FieldAnchorOn, field.TypeString, value)
		_node.AnchorOn = value
	}
	if value, ok := _c.mutation.NextOccurrenceOn(); ok {
		_spec.SetField(subscription.FieldNextOccurrenceOn, field.TypeString, value)
		_node.NextOccurrenceOn = value
	}
	if value, ok := _c.mutation.CoveredThroughOn(); ok {
		_spec.SetField(subscription.FieldCoveredThroughOn, field.TypeString, value)
		_node.CoveredThroughOn = value
	}
	if value, ok := _c.mutation.IntervalMonths(); ok {
		_spec.SetField(subscription.FieldIntervalMonths, field.TypeInt, value)
		_node.IntervalMonths = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(subscription.FieldColor, field.TypeString, value)
		_node.Color = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TemplateEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TemplateEntriesTable,
			Columns: []string{subscription.TemplateEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OccurrencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.OccurrencesTable,
			Columns: []string{subscription.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TransactionsTable,
			Columns: []string{subscription.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EncryptionKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.EncryptionKeyTable,
			Columns: []string{subscription.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ledger_encryption_key_subscriptions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubscriptionCreateBulk is the builder for creating many Subscription entities in bulk.
type SubscriptionCreateBulk struct {
	config
	err      error
	builders []*SubscriptionCreate
}

// Save creates the Subscription entities in the database.
func (_c *SubscriptionCreateBulk) Save(ctx context.Context) ([]*Subscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Subscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) SaveX(ctx context.Context) []*Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
