// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/ledgerencryptionkey"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/ent/subscriptionentry"
	"github.com/suda-3156/kkb/go/ent/subscriptionoccurrence"
	"github.com/suda-3156/kkb/go/ent/transaction"
	"github.com/suda-3156/kkb/go/internal/date"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SubscriptionUpdate) SetName(v []byte) *SubscriptionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetRegisteredOn sets the "registered_on" field.
func (_u *SubscriptionUpdate) SetRegisteredOn(v date.Date) *SubscriptionUpdate {
	_u.mutation.SetRegisteredOn(v)
	return _u
}

// SetNillableRegisteredOn sets the "registered_on" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableRegisteredOn(v *date.Date) *SubscriptionUpdate {
	if v != nil {
		_u.SetRegisteredOn(*v)
	}
	return _u
}

// SetAnchorOn sets the "anchor_on" field.
func (_u *SubscriptionUpdate) SetAnchorOn(v date.Date) *SubscriptionUpdate {
	_u.mutation.SetAnchorOn(v)
	return _u
}

// SetNillableAnchorOn sets the "anchor_on" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableAnchorOn(v *date.Date) *SubscriptionUpdate {
	if v != nil {
		_u.SetAnchorOn(*v)
	}
	return _u
}

// SetNextOccurrenceOn sets the "next_occurrence_on" field.
func (_u *SubscriptionUpdate) SetNextOccurrenceOn(v date.Date) *SubscriptionUpdate {
	_u.mutation.SetNextOccurrenceOn(v)
	return _u
}

// SetNillableNextOccurrenceOn sets the "next_occurrence_on" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableNextOccurrenceOn(v *date.Date) *SubscriptionUpdate {
	if v != nil {
		_u.SetNextOccurrenceOn(*v)
	}
	return _u
}

// SetCoveredThroughOn sets the "covered_through_on" field.
func (_u *SubscriptionUpdate) SetCoveredThroughOn(v date.Date) *SubscriptionUpdate {
	_u.mutation.SetCoveredThroughOn(v)
	return _u
}

// SetNillableCoveredThroughOn sets the "covered_through_on" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCoveredThroughOn(v *date.Date) *SubscriptionUpdate {
	if v != nil {
		_u.SetCoveredThroughOn(*v)
	}
	return _u
}

// SetIntervalMonths sets the "interval_months" field.
func (_u *SubscriptionUpdate) SetIntervalMonths(v int) *SubscriptionUpdate {
	_u.mutation.ResetIntervalMonths()
	_u.mutation.SetIntervalMonths(v)
	return _u
}

// SetNillableIntervalMonths sets the "interval_months" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableIntervalMonths(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetIntervalMonths(*v)
	}
	return _u
}

// AddIntervalMonths adds value to the "interval_months" field.
func (_u *SubscriptionUpdate) AddIntervalMonths(v int) *SubscriptionUpdate {
	_u.mutation.AddIntervalMonths(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdate) SetStatus(v schema.SubscriptionStatus) *SubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStatus(v *schema.SubscriptionStatus) *SubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SubscriptionUpdate) SetColor(v string) *SubscriptionUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableColor(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *SubscriptionUpdate) ClearColor() *SubscriptionUpdate {
	_u.mutation.ClearColor()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdate) SetUpdatedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTemplateEntryIDs adds the "template_entries" edge to the SubscriptionEntry entity by IDs.
func (_u *SubscriptionUpdate) AddTemplateEntryIDs(ids ...int) *SubscriptionUpdate {
	_u.mutation.AddTemplateEntryIDs(ids...)
	return _u
}

// AddTemplateEntries adds the "template_entries" edges to the SubscriptionEntry entity.
func (_u *SubscriptionUpdate) AddTemplateEntries(v ...*SubscriptionEntry) *SubscriptionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTemplateEntryIDs(ids...)
}

// AddOccurrenceIDs adds the "occurrences" edge to the SubscriptionOccurrence entity by IDs.
func (_u *SubscriptionUpdate) AddOccurrenceIDs(ids ...int) *SubscriptionUpdate {
	_u.mutation.AddOccurrenceIDs(ids...)
	return _u
}

// AddOccurrences adds the "occurrences" edges to the SubscriptionOccurrence entity.
func (_u *SubscriptionUpdate) AddOccurrences(v ...*SubscriptionOccurrence) *SubscriptionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOccurrenceIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *SubscriptionUpdate) AddTransactionIDs(ids ...int) *SubscriptionUpdate {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *SubscriptionUpdate) AddTransactions(v ...*Transaction) *SubscriptionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// SetEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID.
func (_u *SubscriptionUpdate) SetEncryptionKeyID(id int) *SubscriptionUpdate {
	_u.mutation.SetEncryptionKeyID(id)
	return _u
}

// SetNillableEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableEncryptionKeyID(id *int) *SubscriptionUpdate {
	if id != nil {
		_u = _u.SetEncryptionKeyID(*id)
	}
	return _u
}

// SetEncryptionKey sets the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *SubscriptionUpdate) SetEncryptionKey(v *LedgerEncryptionKey) *SubscriptionUpdate {
	return _u.SetEncryptionKeyID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearTemplateEntries clears all "template_entries" edges to the SubscriptionEntry entity.
func (_u *SubscriptionUpdate) ClearTemplateEntries() *SubscriptionUpdate {
	_u.mutation.ClearTemplateEntries()
	return _u
}

// RemoveTemplateEntryIDs removes the "template_entries" edge to SubscriptionEntry entities by IDs.
func (_u *SubscriptionUpdate) RemoveTemplateEntryIDs(ids ...int) *SubscriptionUpdate {
	_u.mutation.RemoveTemplateEntryIDs(ids...)
	return _u
}

// RemoveTemplateEntries removes "template_entries" edges to SubscriptionEntry entities.
func (_u *SubscriptionUpdate) RemoveTemplateEntries(v ...*SubscriptionEntry) *SubscriptionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTemplateEntryIDs(ids...)
}

// ClearOccurrences clears all "occurrences" edges to the SubscriptionOccurrence entity.
func (_u *SubscriptionUpdate) ClearOccurrences() *SubscriptionUpdate {
	_u.mutation.ClearOccurrences()
	return _u
}

// RemoveOccurrenceIDs removes the "occurrences" edge to SubscriptionOccurrence entities by IDs.
func (_u *SubscriptionUpdate) RemoveOccurrenceIDs(ids ...int) *SubscriptionUpdate {
	_u.mutation.RemoveOccurrenceIDs(ids...)
	return _u
}

// RemoveOccurrences removes "occurrences" edges to SubscriptionOccurrence entities.
func (_u *SubscriptionUpdate) RemoveOccurrences(v ...*SubscriptionOccurrence) *SubscriptionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOccurrenceIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *SubscriptionUpdate) ClearTransactions() *SubscriptionUpdate {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *SubscriptionUpdate) RemoveTransactionIDs(ids ...int) *SubscriptionUpdate {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *SubscriptionUpdate) RemoveTransactions(v ...*Transaction) *SubscriptionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearEncryptionKey clears the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *SubscriptionUpdate) ClearEncryptionKey() *SubscriptionUpdate {
	_u.mutation.ClearEncryptionKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subscription.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegisteredOn(); ok {
		if err := subscription.RegisteredOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "registered_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.registered_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AnchorOn(); ok {
		if err := subscription.AnchorOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "anchor_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.anchor_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NextOccurrenceOn(); ok {
		if err := subscription.NextOccurrenceOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "next_occurrence_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.next_occurrence_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoveredThroughOn(); ok {
		if err := subscription.CoveredThroughOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "covered_through_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.covered_through_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalMonths(); ok {
		if err := subscription.IntervalMonthsValidator(v); err != nil {
			return &ValidationError{Name: "interval_months", err: fmt.Errorf(`ent: validator failed for field "Subscription.interval_months": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := subscription.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Subscription.color": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscription.FieldName, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.RegisteredOn(); ok {
		_spec.SetField(subscription.FieldRegisteredOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnchorOn(); ok {
		_spec.SetField(subscription.FieldAnchorOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextOccurrenceOn(); ok {
		_spec.SetField(subscription.FieldNextOccurrenceOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoveredThroughOn(); ok {
		_spec.SetField(subscription.FieldCoveredThroughOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntervalMonths(); ok {
		_spec.SetField(subscription.FieldIntervalMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalMonths(); ok {
		_spec.AddField(subscription.FieldIntervalMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(subscription.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(subscription.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TemplateEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TemplateEntriesTable,
			Columns: []string{subscription.TemplateEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTemplateEntriesIDs(); len(nodes) > 0 && !_u.mutation.TemplateEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TemplateEntriesTable,
			Columns: []string{subscription.TemplateEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TemplateEntriesTable,
			Columns: []string{subscription.TemplateEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.OccurrencesTable,
			Columns: []string{subscription.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOccurrencesIDs(); len(nodes) > 0 && !_u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.OccurrencesTable,
			Columns: []string{subscription.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OccurrencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.OccurrencesTable,
			Columns: []string{subscription.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TransactionsTable,
			Columns: []string{subscription.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TransactionsTable,
			Columns: []string{subscription.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TransactionsTable,
			Columns: []string{subscription.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EncryptionKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.EncryptionKeyTable,
			Columns: []string{subscription.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EncryptionKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.EncryptionKeyTable,
			Columns: []string{subscription.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetName sets the "name" field.
func (_u *SubscriptionUpdateOne) SetName(v []byte) *SubscriptionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetRegisteredOn sets the "registered_on" field.
func (_u *SubscriptionUpdateOne) SetRegisteredOn(v date.Date) *SubscriptionUpdateOne {
	_u.mutation.SetRegisteredOn(v)
	return _u
}

// SetNillableRegisteredOn sets the "registered_on" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableRegisteredOn(v *date.Date) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetRegisteredOn(*v)
	}
	return _u
}

// SetAnchorOn sets the "anchor_on" field.
func (_u *SubscriptionUpdateOne) SetAnchorOn(v date.Date) *SubscriptionUpdateOne {
	_u.mutation.SetAnchorOn(v)
	return _u
}

// SetNillableAnchorOn sets the "anchor_on" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableAnchorOn(v *date.Date) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetAnchorOn(*v)
	}
	return _u
}

// SetNextOccurrenceOn sets the "next_occurrence_on" field.
func (_u *SubscriptionUpdateOne) SetNextOccurrenceOn(v date.Date) *SubscriptionUpdateOne {
	_u.mutation.SetNextOccurrenceOn(v)
	return _u
}

// SetNillableNextOccurrenceOn sets the "next_occurrence_on" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableNextOccurrenceOn(v *date.Date) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetNextOccurrenceOn(*v)
	}
	return _u
}

// SetCoveredThroughOn sets the "covered_through_on" field.
func (_u *SubscriptionUpdateOne) SetCoveredThroughOn(v date.Date) *SubscriptionUpdateOne {
	_u.mutation.SetCoveredThroughOn(v)
	return _u
}

// SetNillableCoveredThroughOn sets the "covered_through_on" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCoveredThroughOn(v *date.Date) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCoveredThroughOn(*v)
	}
	return _u
}

// SetIntervalMonths sets the "interval_months" field.
func (_u *SubscriptionUpdateOne) SetIntervalMonths(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetIntervalMonths()
	_u.mutation.SetIntervalMonths(v)
	return _u
}

// SetNillableIntervalMonths sets the "interval_months" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableIntervalMonths(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetIntervalMonths(*v)
	}
	return _u
}

// AddIntervalMonths adds value to the "interval_months" field.
func (_u *SubscriptionUpdateOne) AddIntervalMonths(v int) *SubscriptionUpdateOne {
	_u.mutation.AddIntervalMonths(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdateOne) SetStatus(v schema.SubscriptionStatus) *SubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStatus(v *schema.SubscriptionStatus) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SubscriptionUpdateOne) SetColor(v string) *SubscriptionUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableColor(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *SubscriptionUpdateOne) ClearColor() *SubscriptionUpdateOne {
	_u.mutation.ClearColor()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddTemplateEntryIDs adds the "template_entries" edge to the SubscriptionEntry entity by IDs.
func (_u *SubscriptionUpdateOne) AddTemplateEntryIDs(ids ...int) *SubscriptionUpdateOne {
	_u.mutation.AddTemplateEntryIDs(ids...)
	return _u
}

// AddTemplateEntries adds the "template_entries" edges to the SubscriptionEntry entity.
func (_u *SubscriptionUpdateOne) AddTemplateEntries(v ...*SubscriptionEntry) *SubscriptionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTemplateEntryIDs(ids...)
}

// AddOccurrenceIDs adds the "occurrences" edge to the SubscriptionOccurrence entity by IDs.
func (_u *SubscriptionUpdateOne) AddOccurrenceIDs(ids ...int) *SubscriptionUpdateOne {
	_u.mutation.AddOccurrenceIDs(ids...)
	return _u
}

// AddOccurrences adds the "occurrences" edges to the SubscriptionOccurrence entity.
func (_u *SubscriptionUpdateOne) AddOccurrences(v ...*SubscriptionOccurrence) *SubscriptionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOccurrenceIDs(ids...)
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *SubscriptionUpdateOne) AddTransactionIDs(ids ...int) *SubscriptionUpdateOne {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *SubscriptionUpdateOne) AddTransactions(v ...*Transaction) *SubscriptionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// SetEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID.
func (_u *SubscriptionUpdateOne) SetEncryptionKeyID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetEncryptionKeyID(id)
	return _u
}

// SetNillableEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableEncryptionKeyID(id *int) *SubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetEncryptionKeyID(*id)
	}
	return _u
}

// SetEncryptionKey sets the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *SubscriptionUpdateOne) SetEncryptionKey(v *LedgerEncryptionKey) *SubscriptionUpdateOne {
	return _u.SetEncryptionKeyID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearTemplateEntries clears all "template_entries" edges to the SubscriptionEntry entity.
func (_u *SubscriptionUpdateOne) ClearTemplateEntries() *SubscriptionUpdateOne {
	_u.mutation.ClearTemplateEntries()
	return _u
}

// RemoveTemplateEntryIDs removes the "template_entries" edge to SubscriptionEntry entities by IDs.
func (_u *SubscriptionUpdateOne) RemoveTemplateEntryIDs(ids ...int) *SubscriptionUpdateOne {
	_u.mutation.RemoveTemplateEntryIDs(ids...)
	return _u
}

// RemoveTemplateEntries removes "template_entries" edges to SubscriptionEntry entities.
func (_u *SubscriptionUpdateOne) RemoveTemplateEntries(v ...*SubscriptionEntry) *SubscriptionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTemplateEntryIDs(ids...)
}

// ClearOccurrences clears all "occurrences" edges to the SubscriptionOccurrence entity.
func (_u *SubscriptionUpdateOne) ClearOccurrences() *SubscriptionUpdateOne {
	_u.mutation.ClearOccurrences()
	return _u
}

// RemoveOccurrenceIDs removes the "occurrences" edge to SubscriptionOccurrence entities by IDs.
func (_u *SubscriptionUpdateOne) RemoveOccurrenceIDs(ids ...int) *SubscriptionUpdateOne {
	_u.mutation.RemoveOccurrenceIDs(ids...)
	return _u
}

// RemoveOccurrences removes "occurrences" edges to SubscriptionOccurrence entities.
func (_u *SubscriptionUpdateOne) RemoveOccurrences(v ...*SubscriptionOccurrence) *SubscriptionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOccurrenceIDs(ids...)
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *SubscriptionUpdateOne) ClearTransactions() *SubscriptionUpdateOne {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *SubscriptionUpdateOne) RemoveTransactionIDs(ids ...int) *SubscriptionUpdateOne {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *SubscriptionUpdateOne) RemoveTransactions(v ...*Transaction) *SubscriptionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearEncryptionKey clears the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *SubscriptionUpdateOne) ClearEncryptionKey() *SubscriptionUpdateOne {
	_u.mutation.ClearEncryptionKey()
	return _u
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subscription.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subscription.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegisteredOn(); ok {
		if err := subscription.RegisteredOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "registered_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.registered_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AnchorOn(); ok {
		if err := subscription.AnchorOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "anchor_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.anchor_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NextOccurrenceOn(); ok {
		if err := subscription.NextOccurrenceOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "next_occurrence_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.next_occurrence_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoveredThroughOn(); ok {
		if err := subscription.CoveredThroughOnValidator(string(v)); err != nil {
			return &ValidationError{Name: "covered_through_on", err: fmt.Errorf(`ent: validator failed for field "Subscription.covered_through_on": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalMonths(); ok {
		if err := subscription.IntervalMonthsValidator(v); err != nil {
			return &ValidationError{Name: "interval_months", err: fmt.Errorf(`ent: validator failed for field "Subscription.interval_months": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := subscription.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Subscription.color": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subscription.FieldName, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.RegisteredOn(); ok {
		_spec.SetField(subscription.FieldRegisteredOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnchorOn(); ok {
		_spec.SetField(subscription.FieldAnchorOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextOccurrenceOn(); ok {
		_spec.SetField(subscription.FieldNextOccurrenceOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoveredThroughOn(); ok {
		_spec.SetField(subscription.FieldCoveredThroughOn, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntervalMonths(); ok {
		_spec.SetField(subscription.FieldIntervalMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalMonths(); ok {
		_spec.AddField(subscription.FieldIntervalMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(subscription.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(subscription.FieldColor, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TemplateEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TemplateEntriesTable,
			Columns: []string{subscription.TemplateEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTemplateEntriesIDs(); len(nodes) > 0 && !_u.mutation.TemplateEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TemplateEntriesTable,
			Columns: []string{subscription.TemplateEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TemplateEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TemplateEntriesTable,
			Columns: []string{subscription.TemplateEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.OccurrencesTable,
			Columns: []string{subscription.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOccurrencesIDs(); len(nodes) > 0 && !_u.mutation.OccurrencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.OccurrencesTable,
			Columns: []string{subscription.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OccurrencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.OccurrencesTable,
			Columns: []string{subscription.OccurrencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionoccurrence.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TransactionsTable,
			Columns: []string{subscription.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TransactionsTable,
			Columns: []string{subscription.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.TransactionsTable,
			Columns: []string{subscription.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EncryptionKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.EncryptionKeyTable,
			Columns: []string{subscription.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EncryptionKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.EncryptionKeyTable,
			Columns: []string{subscription.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
