// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/suda-3156/kkb/go/ent/ledgeraccount"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/ent/subscriptionentry"
)

// SubscriptionEntry is the model entity for the SubscriptionEntry schema.
type SubscriptionEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int32 `json:"amount,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind schema.JournalEntryKind `json:"kind,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionEntryQuery when eager-loading is set.
	Edges                               SubscriptionEntryEdges `json:"edges"`
	ledger_account_subscription_entries *int
	subscription_template_entries       *int
	selectValues                        sql.SelectValues
}

// SubscriptionEntryEdges holds the relations/edges for other nodes in the graph.
type SubscriptionEntryEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *Subscription `json:"subscription,omitempty"`
	// LedgerAccount holds the value of the ledger_account edge.
	LedgerAccount *LedgerAccount `json:"ledger_account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionEntryEdges) SubscriptionOrErr() (*Subscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// LedgerAccountOrErr returns the LedgerAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionEntryEdges) LedgerAccountOrErr() (*LedgerAccount, error) {
	if e.LedgerAccount != nil {
		return e.LedgerAccount, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: ledgeraccount.Label}
	}
	return nil, &NotLoadedError{edge: "ledger_account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionentry.FieldID, subscriptionentry.FieldAmount:
			values[i] = new(sql.NullInt64)
		case subscriptionentry.FieldKind:
			values[i] = new(sql.NullString)
		case subscriptionentry.ForeignKeys[0]: // ledger_account_subscription_entries
			values[i] = new(sql.NullInt64)
		case subscriptionentry.ForeignKeys[1]: // subscription_template_entries
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionEntry fields.
func (_m *SubscriptionEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case subscriptionentry.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = int32(value.Int64)
			}
		case subscriptionentry.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = schema.JournalEntryKind(value.String)
			}
		case subscriptionentry.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ledger_account_subscription_entries", value)
			} else if value.Valid {
				_m.ledger_account_subscription_entries = new(int)
				*_m.ledger_account_subscription_entries = int(value.Int64)
			}
		case subscriptionentry.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field subscription_template_entries", value)
			} else if value.Valid {
				_m.subscription_template_entries = new(int)
				*_m.subscription_template_entries = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionEntry.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionEntry entity.
func (_m *SubscriptionEntry) QuerySubscription() *SubscriptionQuery {
	return NewSubscriptionEntryClient(_m.config).QuerySubscription(_m)
}

// QueryLedgerAccount queries the "ledger_account" edge of the SubscriptionEntry entity.
func (_m *SubscriptionEntry) QueryLedgerAccount() *LedgerAccountQuery {
	return NewSubscriptionEntryClient(_m.config).QueryLedgerAccount(_m)
}

// Update returns a builder for updating this SubscriptionEntry.
// Note that you need to call SubscriptionEntry.Unwrap() before calling this method if this SubscriptionEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionEntry) Update() *SubscriptionEntryUpdateOne {
	return NewSubscriptionEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionEntry) Unwrap() *SubscriptionEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionEntry) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionEntries is a parsable slice of SubscriptionEntry.
type SubscriptionEntries []*SubscriptionEntry
