// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/ent/subscription"
	"github.com/suda-3156/kkb/go/ent/subscriptionoccurrence"
	"github.com/suda-3156/kkb/go/internal/date"
)

// SubscriptionOccurrence is the model entity for the SubscriptionOccurrence schema.
type SubscriptionOccurrence struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OccurrenceOn holds the value of the "occurrence_on" field.
	OccurrenceOn date.Date `json:"occurrence_on,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome schema.OccurrenceOutcome `json:"outcome,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionOccurrenceQuery when eager-loading is set.
	Edges                    SubscriptionOccurrenceEdges `json:"edges"`
	subscription_occurrences *int
	selectValues             sql.SelectValues
}

// SubscriptionOccurrenceEdges holds the relations/edges for other nodes in the graph.
type SubscriptionOccurrenceEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *Subscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionOccurrenceEdges) SubscriptionOrErr() (*Subscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionOccurrence) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionoccurrence.FieldID:
			values[i] = new(sql.NullInt64)
		case subscriptionoccurrence.FieldOccurrenceOn, subscriptionoccurrence.FieldOutcome:
			values[i] = new(sql.NullString)
		case subscriptionoccurrence.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case subscriptionoccurrence.ForeignKeys[0]: // subscription_occurrences
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionOccurrence fields.
func (_m *SubscriptionOccurrence) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionoccurrence.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case subscriptionoccurrence.FieldOccurrenceOn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field occurrence_on", values[i])
			} else if value.Valid {
				_m.OccurrenceOn = date.Date(value.String)
			}
		case subscriptionoccurrence.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = schema.OccurrenceOutcome(value.String)
			}
		case subscriptionoccurrence.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionoccurrence.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field subscription_occurrences", value)
			} else if value.Valid {
				_m.subscription_occurrences = new(int)
				*_m.subscription_occurrences = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionOccurrence.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionOccurrence) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionOccurrence entity.
func (_m *SubscriptionOccurrence) QuerySubscription() *SubscriptionQuery {
	return NewSubscriptionOccurrenceClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this SubscriptionOccurrence.
// Note that you need to call SubscriptionOccurrence.Unwrap() before calling this method if this SubscriptionOccurrence
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionOccurrence) Update() *SubscriptionOccurrenceUpdateOne {
	return NewSubscriptionOccurrenceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionOccurrence entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionOccurrence) Unwrap() *SubscriptionOccurrence {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionOccurrence is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionOccurrence) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionOccurrence(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("occurrence_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.OccurrenceOn))
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outcome))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionOccurrences is a parsable slice of SubscriptionOccurrence.
type SubscriptionOccurrences []*SubscriptionOccurrence
