// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/suda-3156/kkb/go/ent/ledgerencryptionkey"
	"github.com/suda-3156/kkb/go/ent/transaction"
	"github.com/suda-3156/kkb/go/internal/date"
	"github.com/suda-3156/kkb/go/internal/prid"
)

// Transaction is the model entity for the Transaction schema.
type Transaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID prid.ID `json:"public_id,omitempty"`
	// Date holds the value of the "date" field.
	Date date.Date `json:"date,omitempty"`
	// Description holds the value of the "description" field.
	Description []byte `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransactionQuery when eager-loading is set.
	Edges                              TransactionEdges `json:"edges"`
	ledger_encryption_key_transactions *int
	selectValues                       sql.SelectValues
}

// TransactionEdges holds the relations/edges for other nodes in the graph.
type TransactionEdges struct {
	// Entries holds the value of the entries edge.
	Entries []*JournalEntry `json:"entries,omitempty"`
	// EncryptionKey holds the value of the encryption_key edge.
	EncryptionKey *LedgerEncryptionKey `json:"encryption_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EntriesOrErr returns the Entries value or an error if the edge
// was not loaded in eager-loading.
func (e TransactionEdges) EntriesOrErr() ([]*JournalEntry, error) {
	if e.loadedTypes[0] {
		return e.Entries, nil
	}
	return nil, &NotLoadedError{edge: "entries"}
}

// EncryptionKeyOrErr returns the EncryptionKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) EncryptionKeyOrErr() (*LedgerEncryptionKey, error) {
	if e.EncryptionKey != nil {
		return e.EncryptionKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: ledgerencryptionkey.Label}
	}
	return nil, &NotLoadedError{edge: "encryption_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Transaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transaction.FieldDescription:
			values[i] = new([]byte)
		case transaction.FieldPublicID:
			values[i] = new(prid.ID)
		case transaction.FieldID:
			values[i] = new(sql.NullInt64)
		case transaction.FieldDate:
			values[i] = new(sql.NullString)
		case transaction.FieldCreatedAt, transaction.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case transaction.ForeignKeys[0]: // ledger_encryption_key_transactions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Transaction fields.
func (_m *Transaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case transaction.FieldPublicID:
			if value, ok := values[i].(*prid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case transaction.FieldDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = date.Date(value.String)
			}
		case transaction.FieldDescription:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value != nil {
				_m.Description = *value
			}
		case transaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case transaction.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case transaction.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ledger_encryption_key_transactions", value)
			} else if value.Valid {
				_m.ledger_encryption_key_transactions = new(int)
				*_m.ledger_encryption_key_transactions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Transaction.
// This includes values selected through modifiers, order, etc.
func (_m *Transaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntries queries the "entries" edge of the Transaction entity.
func (_m *Transaction) QueryEntries() *JournalEntryQuery {
	return NewTransactionClient(_m.config).QueryEntries(_m)
}

// QueryEncryptionKey queries the "encryption_key" edge of the Transaction entity.
func (_m *Transaction) QueryEncryptionKey() *LedgerEncryptionKeyQuery {
	return NewTransactionClient(_m.config).QueryEncryptionKey(_m)
}

// Update returns a builder for updating this Transaction.
// Note that you need to call Transaction.Unwrap() before calling this method if this Transaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Transaction) Update() *TransactionUpdateOne {
	return NewTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Transaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Transaction) Unwrap() *Transaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Transaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Transaction) String() string {
	var builder strings.Builder
	builder.WriteString("Transaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(fmt.Sprintf("%v", _m.Date))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(fmt.Sprintf("%v", _m.Description))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Transactions is a parsable slice of Transaction.
type Transactions []*Transaction
