// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suda-3156/kkb/go/ent/journalentry"
	"github.com/suda-3156/kkb/go/ent/ledgerencryptionkey"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/transaction"
	"github.com/suda-3156/kkb/go/internal/date"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDate sets the "date" field.
func (_u *TransactionUpdate) SetDate(v date.Date) *TransactionUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TransactionUpdate) SetNillableDate(v *date.Date) *TransactionUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdate) SetDescription(v []byte) *TransactionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdate) SetUpdatedAt(v time.Time) *TransactionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEntryIDs adds the "entries" edge to the JournalEntry entity by IDs.
func (_u *TransactionUpdate) AddEntryIDs(ids ...int) *TransactionUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the JournalEntry entity.
func (_u *TransactionUpdate) AddEntries(v ...*JournalEntry) *TransactionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// SetEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID.
func (_u *TransactionUpdate) SetEncryptionKeyID(id int) *TransactionUpdate {
	_u.mutation.SetEncryptionKeyID(id)
	return _u
}

// SetNillableEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID if the given value is not nil.
func (_u *TransactionUpdate) SetNillableEncryptionKeyID(id *int) *TransactionUpdate {
	if id != nil {
		_u = _u.SetEncryptionKeyID(*id)
	}
	return _u
}

// SetEncryptionKey sets the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *TransactionUpdate) SetEncryptionKey(v *LedgerEncryptionKey) *TransactionUpdate {
	return _u.SetEncryptionKeyID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdate) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearEntries clears all "entries" edges to the JournalEntry entity.
func (_u *TransactionUpdate) ClearEntries() *TransactionUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to JournalEntry entities by IDs.
func (_u *TransactionUpdate) RemoveEntryIDs(ids ...int) *TransactionUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to JournalEntry entities.
func (_u *TransactionUpdate) RemoveEntries(v ...*JournalEntry) *TransactionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearEncryptionKey clears the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *TransactionUpdate) ClearEncryptionKey() *TransactionUpdate {
	_u.mutation.ClearEncryptionKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdate) check() error {
	if v, ok := _u.mutation.Date(); ok {
		if err := transaction.DateValidator(string(v)); err != nil {
			return &ValidationError{Name: "date", err: fmt.Errorf(`ent: validator failed for field "Transaction.date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := transaction.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Transaction.description": %w`, err)}
		}
	}
	return nil
}

func (_u *TransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.EntriesTable,
			Columns: []string{transaction.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.EntriesTable,
			Columns: []string{transaction.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.EntriesTable,
			Columns: []string{transaction.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EncryptionKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.EncryptionKeyTable,
			Columns: []string{transaction.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EncryptionKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.EncryptionKeyTable,
			Columns: []string{transaction.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetDate sets the "date" field.
func (_u *TransactionUpdateOne) SetDate(v date.Date) *TransactionUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableDate(v *date.Date) *TransactionUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TransactionUpdateOne) SetDescription(v []byte) *TransactionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TransactionUpdateOne) SetUpdatedAt(v time.Time) *TransactionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEntryIDs adds the "entries" edge to the JournalEntry entity by IDs.
func (_u *TransactionUpdateOne) AddEntryIDs(ids ...int) *TransactionUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the JournalEntry entity.
func (_u *TransactionUpdateOne) AddEntries(v ...*JournalEntry) *TransactionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// SetEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID.
func (_u *TransactionUpdateOne) SetEncryptionKeyID(id int) *TransactionUpdateOne {
	_u.mutation.SetEncryptionKeyID(id)
	return _u
}

// SetNillableEncryptionKeyID sets the "encryption_key" edge to the LedgerEncryptionKey entity by ID if the given value is not nil.
func (_u *TransactionUpdateOne) SetNillableEncryptionKeyID(id *int) *TransactionUpdateOne {
	if id != nil {
		_u = _u.SetEncryptionKeyID(*id)
	}
	return _u
}

// SetEncryptionKey sets the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *TransactionUpdateOne) SetEncryptionKey(v *LedgerEncryptionKey) *TransactionUpdateOne {
	return _u.SetEncryptionKeyID(v.ID)
}

// Mutation returns the TransactionMutation object of the builder.
func (_u *TransactionUpdateOne) Mutation() *TransactionMutation {
	return _u.mutation
}

// ClearEntries clears all "entries" edges to the JournalEntry entity.
func (_u *TransactionUpdateOne) ClearEntries() *TransactionUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to JournalEntry entities by IDs.
func (_u *TransactionUpdateOne) RemoveEntryIDs(ids ...int) *TransactionUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to JournalEntry entities.
func (_u *TransactionUpdateOne) RemoveEntries(v ...*JournalEntry) *TransactionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// ClearEncryptionKey clears the "encryption_key" edge to the LedgerEncryptionKey entity.
func (_u *TransactionUpdateOne) ClearEncryptionKey() *TransactionUpdateOne {
	_u.mutation.ClearEncryptionKey()
	return _u
}

// Where appends a list predicates to the TransactionUpdate builder.
func (_u *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Transaction entity.
func (_u *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TransactionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := transaction.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionUpdateOne) check() error {
	if v, ok := _u.mutation.Date(); ok {
		if err := transaction.DateValidator(string(v)); err != nil {
			return &ValidationError{Name: "date", err: fmt.Errorf(`ent: validator failed for field "Transaction.date": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := transaction.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Transaction.description": %w`, err)}
		}
	}
	return nil
}

func (_u *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(transaction.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.EntriesTable,
			Columns: []string{transaction.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.EntriesTable,
			Columns: []string{transaction.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   transaction.EntriesTable,
			Columns: []string{transaction.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EncryptionKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.EncryptionKeyTable,
			Columns: []string{transaction.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EncryptionKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   transaction.EncryptionKeyTable,
			Columns: []string{transaction.EncryptionKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ledgerencryptionkey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
