// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// JournalEntriesColumns holds the columns for the "journal_entries" table.
	JournalEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeInt32},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"DEBIT", "CREDIT"}},
		{Name: "ledger_account_journal_entries", Type: field.TypeInt},
		{Name: "transaction_entries", Type: field.TypeInt},
	}
	// JournalEntriesTable holds the schema information for the "journal_entries" table.
	JournalEntriesTable = &schema.Table{
		Name:       "journal_entries",
		Columns:    JournalEntriesColumns,
		PrimaryKey: []*schema.Column{JournalEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "journal_entries_ledger_accounts_journal_entries",
				Columns:    []*schema.Column{JournalEntriesColumns[3]},
				RefColumns: []*schema.Column{LedgerAccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "journal_entries_transactions_entries",
				Columns:    []*schema.Column{JournalEntriesColumns[4]},
				RefColumns: []*schema.Column{TransactionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// LedgerAccountsColumns holds the columns for the "ledger_accounts" table.
	LedgerAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_id", Type: field.TypeString, Unique: true, Size: 20, SchemaType: map[string]string{"mysql": "char(20)"}},
		{Name: "account_name", Type: field.TypeBytes, Size: 512},
		{Name: "kind", Type: field.TypeEnum, Enums: []string{"ASSET", "LIABILITY", "EXPENSE", "REVENUE", "EQUITY"}},
		{Name: "is_group", Type: field.TypeBool},
		{Name: "archived_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "ledger_account_children", Type: field.TypeInt, Nullable: true},
		{Name: "ledger_encryption_key_ledger_accounts", Type: field.TypeInt, Nullable: true},
	}
	// LedgerAccountsTable holds the schema information for the "ledger_accounts" table.
	LedgerAccountsTable = &schema.Table{
		Name:       "ledger_accounts",
		Columns:    LedgerAccountsColumns,
		PrimaryKey: []*schema.Column{LedgerAccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ledger_accounts_ledger_accounts_children",
				Columns:    []*schema.Column{LedgerAccountsColumns[8]},
				RefColumns: []*schema.Column{LedgerAccountsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "ledger_accounts_ledger_encryption_keys_ledger_accounts",
				Columns:    []*schema.Column{LedgerAccountsColumns[9]},
				RefColumns: []*schema.Column{LedgerEncryptionKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// LedgerEncryptionKeysColumns holds the columns for the "ledger_encryption_keys" table.
	LedgerEncryptionKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "aad", Type: field.TypeBytes, Size: 32},
		{Name: "wrapped_cipher", Type: field.TypeBytes, Size: 256},
		{Name: "allowed", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)"}},
	}
	// LedgerEncryptionKeysTable holds the schema information for the "ledger_encryption_keys" table.
	LedgerEncryptionKeysTable = &schema.Table{
		Name:       "ledger_encryption_keys",
		Columns:    LedgerEncryptionKeysColumns,
		PrimaryKey: []*schema.Column{LedgerEncryptionKeysColumns[0]},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "public_id", Type: field.TypeString, Unique: true, Size: 20, SchemaType: map[string]string{"mysql": "char(20)"}},
		{Name: "date", Type: field.TypeString, Size: 10, SchemaType: map[string]string{"mysql": "char(10)"}},
		{Name: "description", Type: field.TypeBytes, Size: 1536},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime(6)"}},
		{Name: "ledger_encryption_key_transactions", Type: field.TypeInt, Nullable: true},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_ledger_encryption_keys_transactions",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{LedgerEncryptionKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		JournalEntriesTable,
		LedgerAccountsTable,
		LedgerEncryptionKeysTable,
		TransactionsTable,
	}
)

func init() {
	JournalEntriesTable.ForeignKeys[0].RefTable = LedgerAccountsTable
	JournalEntriesTable.ForeignKeys[1].RefTable = TransactionsTable
	LedgerAccountsTable.ForeignKeys[0].RefTable = LedgerAccountsTable
	LedgerAccountsTable.ForeignKeys[1].RefTable = LedgerEncryptionKeysTable
	TransactionsTable.ForeignKeys[0].RefTable = LedgerEncryptionKeysTable
}
