// Code generated by ent, DO NOT EDIT.

package subscriptionoccurrence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/schema"
	"github.com/suda-3156/kkb/go/internal/date"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldLTE(FieldID, id))
}

// OccurrenceOn applies equality check predicate on the "occurrence_on" field. It's identical to OccurrenceOnEQ.
func OccurrenceOn(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldEQ(FieldOccurrenceOn, vc))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldEQ(FieldCreatedAt, v))
}

// OccurrenceOnEQ applies the EQ predicate on the "occurrence_on" field.
func OccurrenceOnEQ(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldEQ(FieldOccurrenceOn, vc))
}

// OccurrenceOnNEQ applies the NEQ predicate on the "occurrence_on" field.
func OccurrenceOnNEQ(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldNEQ(FieldOccurrenceOn, vc))
}

// OccurrenceOnIn applies the In predicate on the "occurrence_on" field.
func OccurrenceOnIn(vs ...date.Date) predicate.SubscriptionOccurrence {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.SubscriptionOccurrence(sql.FieldIn(FieldOccurrenceOn, v...))
}

// OccurrenceOnNotIn applies the NotIn predicate on the "occurrence_on" field.
func OccurrenceOnNotIn(vs ...date.Date) predicate.SubscriptionOccurrence {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.SubscriptionOccurrence(sql.FieldNotIn(FieldOccurrenceOn, v...))
}

// OccurrenceOnGT applies the GT predicate on the "occurrence_on" field.
func OccurrenceOnGT(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldGT(FieldOccurrenceOn, vc))
}

// OccurrenceOnGTE applies the GTE predicate on the "occurrence_on" field.
func OccurrenceOnGTE(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldGTE(FieldOccurrenceOn, vc))
}

// OccurrenceOnLT applies the LT predicate on the "occurrence_on" field.
func OccurrenceOnLT(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldLT(FieldOccurrenceOn, vc))
}

// OccurrenceOnLTE applies the LTE predicate on the "occurrence_on" field.
func OccurrenceOnLTE(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldLTE(FieldOccurrenceOn, vc))
}

// OccurrenceOnContains applies the Contains predicate on the "occurrence_on" field.
func OccurrenceOnContains(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldContains(FieldOccurrenceOn, vc))
}

// OccurrenceOnHasPrefix applies the HasPrefix predicate on the "occurrence_on" field.
func OccurrenceOnHasPrefix(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldHasPrefix(FieldOccurrenceOn, vc))
}

// OccurrenceOnHasSuffix applies the HasSuffix predicate on the "occurrence_on" field.
func OccurrenceOnHasSuffix(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldHasSuffix(FieldOccurrenceOn, vc))
}

// OccurrenceOnEqualFold applies the EqualFold predicate on the "occurrence_on" field.
func OccurrenceOnEqualFold(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldEqualFold(FieldOccurrenceOn, vc))
}

// OccurrenceOnContainsFold applies the ContainsFold predicate on the "occurrence_on" field.
func OccurrenceOnContainsFold(v date.Date) predicate.SubscriptionOccurrence {
	vc := string(v)
	return predicate.SubscriptionOccurrence(sql.FieldContainsFold(FieldOccurrenceOn, vc))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v schema.OccurrenceOutcome) predicate.SubscriptionOccurrence {
	vc := v
	return predicate.SubscriptionOccurrence(sql.FieldEQ(FieldOutcome, vc))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v schema.OccurrenceOutcome) predicate.SubscriptionOccurrence {
	vc := v
	return predicate.SubscriptionOccurrence(sql.FieldNEQ(FieldOutcome, vc))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...schema.OccurrenceOutcome) predicate.SubscriptionOccurrence {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SubscriptionOccurrence(sql.FieldIn(FieldOutcome, v...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...schema.OccurrenceOutcome) predicate.SubscriptionOccurrence {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SubscriptionOccurrence(sql.FieldNotIn(FieldOutcome, v...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.Subscription) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionOccurrence) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionOccurrence) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionOccurrence) predicate.SubscriptionOccurrence {
	return predicate.SubscriptionOccurrence(sql.NotPredicates(p))
}
