// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LedgerAccount is the predicate function for ledgeraccount builders.
type LedgerAccount func(*sql.Selector)
