# Docker image for Go API Development
FROM golang:1.26-alpine@sha256:70b46548e42db77e0966aaf3619fd068734dc6c77584d526b91126504fd95816

WORKDIR /app

RUN apk update && apk upgrade && \
    apk add --no-cache git curl bash

RUN go install github.com/air-verse/air@latest

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
