# Docker image for Go API Development
FROM golang:1.26-alpine@sha256:3889b425f035be855a72fb4755265311293b6d414521f0a519d819df32222d83

WORKDIR /app

RUN apk update && apk upgrade && \
    apk add --no-cache git curl bash

RUN go install github.com/air-verse/air@latest

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
