# Docker image for Go API Development
FROM golang:1.27-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125

WORKDIR /app

RUN apk update && apk upgrade && \
    apk add --no-cache git curl bash

RUN go install github.com/air-verse/air@latest

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
