// Code generated by ent, DO NOT EDIT.

package journalentry

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/suda-3156/kkb/go/ent/schema"
)

const (
	// Label holds the string label denoting the journalentry type in the database.
	Label = "journal_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// EdgeTransaction holds the string denoting the transaction edge name in mutations.
	EdgeTransaction = "transaction"
	// EdgeLedgerAccount holds the string denoting the ledger_account edge name in mutations.
	EdgeLedgerAccount = "ledger_account"
	// Table holds the table name of the journalentry in the database.
	Table = "journal_entries"
	// TransactionTable is the table that holds the transaction relation/edge.
	TransactionTable = "journal_entries"
	// TransactionInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionInverseTable = "transactions"
	// TransactionColumn is the table column denoting the transaction relation/edge.
	TransactionColumn = "transaction_entries"
	// LedgerAccountTable is the table that holds the ledger_account relation/edge.
	LedgerAccountTable = "journal_entries"
	// LedgerAccountInverseTable is the table name for the LedgerAccount entity.
	// It exists in this package in order to avoid circular dependency with the "ledgeraccount" package.
	LedgerAccountInverseTable = "ledger_accounts"
	// LedgerAccountColumn is the table column denoting the ledger_account relation/edge.
	LedgerAccountColumn = "ledger_account_journal_entries"
)

// Columns holds all SQL columns for journalentry fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldKind,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "journal_entries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ledger_account_journal_entries",
	"transaction_entries",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(int32) error
)

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k schema.JournalEntryKind) error {
	switch k.String() {
	case "DEBIT", "CREDIT":
		return nil
	default:
		return fmt.Errorf("journalentry: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the JournalEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByTransactionField orders the results by transaction field.
func ByTransactionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransactionStep(), sql.OrderByField(field, opts...))
	}
}

// ByLedgerAccountField orders the results by ledger_account field.
func ByLedgerAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedgerAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newTransactionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransactionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TransactionTable, TransactionColumn),
	)
}
func newLedgerAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedgerAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LedgerAccountTable, LedgerAccountColumn),
	)
}
