// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/suda-3156/kkb/go/pkg/date"
	"github.com/suda-3156/kkb/go/pkg/pulid"
)

type Node interface {
	IsNode()
	GetID() pulid.ID
}

type CreateLedgerAccountInput struct {
	ParentID *pulid.ID         `json:"parentId,omitempty"`
	Name     string            `json:"name"`
	Kind     LedgerAccountKind `json:"kind"`
	IsGroup  bool              `json:"isGroup"`
}

type CreateTransactionInput struct {
	Entries     []*JournalEntryInput `json:"entries"`
	Date        date.Date            `json:"date"`
	Description string               `json:"description"`
}

type DeleteTransactionPayload struct {
	Success bool `json:"success"`
}

type JournalEntryInput struct {
	LedgerAccountID pulid.ID         `json:"ledgerAccountId"`
	Amount          int32            `json:"amount"`
	Kind            JournalEntryKind `json:"kind"`
}

type LedgerAccount struct {
	ID         pulid.ID          `json:"id"`
	Parent     *LedgerAccount    `json:"parent,omitempty"`
	Name       string            `json:"name"`
	Kind       LedgerAccountKind `json:"kind"`
	IsGroup    bool              `json:"isGroup"`
	IsArchived bool              `json:"isArchived"`
	CreatedAt  time.Time         `json:"createdAt"`
	UpdatedAt  time.Time         `json:"updatedAt"`
}

func (LedgerAccount) IsNode()              {}
func (this LedgerAccount) GetID() pulid.ID { return this.ID }

type LedgerAccountConnection struct {
	Edges      []*LedgerAccountEdge `json:"edges,omitempty"`
	Nodes      []*LedgerAccount     `json:"nodes,omitempty"`
	PageInfo   *PageInfo            `json:"pageInfo"`
	TotalCount int32                `json:"totalCount"`
}

type LedgerAccountEdge struct {
	Cursor pulid.ID       `json:"cursor"`
	Node   *LedgerAccount `json:"node"`
}

type Mutation struct {
}

type PageInfo struct {
	StartCursor     *pulid.ID `json:"startCursor,omitempty"`
	EndCursor       *pulid.ID `json:"endCursor,omitempty"`
	HasPreviousPage bool      `json:"hasPreviousPage"`
	HasNextPage     bool      `json:"hasNextPage"`
}

type Query struct {
}

type Transaction struct {
	ID          pulid.ID        `json:"id"`
	Entries     []*JournalEntry `json:"entries"`
	Date        date.Date       `json:"date"`
	Description string          `json:"description"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

func (Transaction) IsNode()              {}
func (this Transaction) GetID() pulid.ID { return this.ID }

type TransactionConnection struct {
	Edges      []*TransactionEdge `json:"edges,omitempty"`
	Nodes      []*Transaction     `json:"nodes,omitempty"`
	PageInfo   *PageInfo          `json:"pageInfo"`
	TotalCount int32              `json:"totalCount"`
}

type TransactionEdge struct {
	Cursor pulid.ID     `json:"cursor"`
	Node   *Transaction `json:"node"`
}

type UpdateLedgerAccountInput struct {
	ID          pulid.ID  `json:"id"`
	ParentID    *pulid.ID `json:"parentId,omitempty"`
	UnsetParent *bool     `json:"unsetParent,omitempty"`
	Name        *string   `json:"name,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type UpdateTransactionInput struct {
	ID          pulid.ID             `json:"id"`
	Entries     []*JournalEntryInput `json:"entries,omitempty"`
	Date        *date.Date           `json:"date,omitempty"`
	Description *string              `json:"description,omitempty"`
	UpdatedAt   time.Time            `json:"updatedAt"`
}

type JournalEntryKind string

const (
	JournalEntryKindDebit  JournalEntryKind = "DEBIT"
	JournalEntryKindCredit JournalEntryKind = "CREDIT"
)

var AllJournalEntryKind = []JournalEntryKind{
	JournalEntryKindDebit,
	JournalEntryKindCredit,
}

func (e JournalEntryKind) IsValid() bool {
	switch e {
	case JournalEntryKindDebit, JournalEntryKindCredit:
		return true
	}
	return false
}

func (e JournalEntryKind) String() string {
	return string(e)
}

func (e *JournalEntryKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JournalEntryKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JournalEntryKind", str)
	}
	return nil
}

func (e JournalEntryKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JournalEntryKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JournalEntryKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LedgerAccountKind string

const (
	LedgerAccountKindAsset     LedgerAccountKind = "ASSET"
	LedgerAccountKindLiability LedgerAccountKind = "LIABILITY"
	LedgerAccountKindExpense   LedgerAccountKind = "EXPENSE"
	LedgerAccountKindRevenue   LedgerAccountKind = "REVENUE"
	LedgerAccountKindEquity    LedgerAccountKind = "EQUITY"
)

var AllLedgerAccountKind = []LedgerAccountKind{
	LedgerAccountKindAsset,
	LedgerAccountKindLiability,
	LedgerAccountKindExpense,
	LedgerAccountKindRevenue,
	LedgerAccountKindEquity,
}

func (e LedgerAccountKind) IsValid() bool {
	switch e {
	case LedgerAccountKindAsset, LedgerAccountKindLiability, LedgerAccountKindExpense, LedgerAccountKindRevenue, LedgerAccountKindEquity:
		return true
	}
	return false
}

func (e LedgerAccountKind) String() string {
	return string(e)
}

func (e *LedgerAccountKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LedgerAccountKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LedgerAccountKind", str)
	}
	return nil
}

func (e LedgerAccountKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LedgerAccountKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LedgerAccountKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
