// Code generated by ent, DO NOT EDIT.

package subscriptionentry

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/suda-3156/kkb/go/ent/predicate"
	"github.com/suda-3156/kkb/go/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldLTE(FieldID, id))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldEQ(FieldAmount, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int32) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.FieldLTE(FieldAmount, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v schema.JournalEntryKind) predicate.SubscriptionEntry {
	vc := v
	return predicate.SubscriptionEntry(sql.FieldEQ(FieldKind, vc))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v schema.JournalEntryKind) predicate.SubscriptionEntry {
	vc := v
	return predicate.SubscriptionEntry(sql.FieldNEQ(FieldKind, vc))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...schema.JournalEntryKind) predicate.SubscriptionEntry {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SubscriptionEntry(sql.FieldIn(FieldKind, v...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...schema.JournalEntryKind) predicate.SubscriptionEntry {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SubscriptionEntry(sql.FieldNotIn(FieldKind, v...))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.Subscription) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgerAccount applies the HasEdge predicate on the "ledger_account" edge.
func HasLedgerAccount() predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LedgerAccountTable, LedgerAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerAccountWith applies the HasEdge predicate on the "ledger_account" edge with a given conditions (other predicates).
func HasLedgerAccountWith(preds ...predicate.LedgerAccount) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(func(s *sql.Selector) {
		step := newLedgerAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionEntry) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionEntry) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionEntry) predicate.SubscriptionEntry {
	return predicate.SubscriptionEntry(sql.NotPredicates(p))
}
