// Code generated by ent, DO NOT EDIT.

package ledgerencryptionkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/suda-3156/kkb/go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLTE(FieldID, id))
}

// Aad applies equality check predicate on the "aad" field. It's identical to AadEQ.
func Aad(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldAad, v))
}

// WrappedCipher applies equality check predicate on the "wrapped_cipher" field. It's identical to WrappedCipherEQ.
func WrappedCipher(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldWrappedCipher, v))
}

// Allowed applies equality check predicate on the "allowed" field. It's identical to AllowedEQ.
func Allowed(v bool) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldAllowed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// AadEQ applies the EQ predicate on the "aad" field.
func AadEQ(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldAad, v))
}

// AadNEQ applies the NEQ predicate on the "aad" field.
func AadNEQ(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNEQ(FieldAad, v))
}

// AadIn applies the In predicate on the "aad" field.
func AadIn(vs ...[]byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldIn(FieldAad, vs...))
}

// AadNotIn applies the NotIn predicate on the "aad" field.
func AadNotIn(vs ...[]byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNotIn(FieldAad, vs...))
}

// AadGT applies the GT predicate on the "aad" field.
func AadGT(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGT(FieldAad, v))
}

// AadGTE applies the GTE predicate on the "aad" field.
func AadGTE(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGTE(FieldAad, v))
}

// AadLT applies the LT predicate on the "aad" field.
func AadLT(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLT(FieldAad, v))
}

// AadLTE applies the LTE predicate on the "aad" field.
func AadLTE(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLTE(FieldAad, v))
}

// WrappedCipherEQ applies the EQ predicate on the "wrapped_cipher" field.
func WrappedCipherEQ(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldWrappedCipher, v))
}

// WrappedCipherNEQ applies the NEQ predicate on the "wrapped_cipher" field.
func WrappedCipherNEQ(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNEQ(FieldWrappedCipher, v))
}

// WrappedCipherIn applies the In predicate on the "wrapped_cipher" field.
func WrappedCipherIn(vs ...[]byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldIn(FieldWrappedCipher, vs...))
}

// WrappedCipherNotIn applies the NotIn predicate on the "wrapped_cipher" field.
func WrappedCipherNotIn(vs ...[]byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNotIn(FieldWrappedCipher, vs...))
}

// WrappedCipherGT applies the GT predicate on the "wrapped_cipher" field.
func WrappedCipherGT(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGT(FieldWrappedCipher, v))
}

// WrappedCipherGTE applies the GTE predicate on the "wrapped_cipher" field.
func WrappedCipherGTE(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGTE(FieldWrappedCipher, v))
}

// WrappedCipherLT applies the LT predicate on the "wrapped_cipher" field.
func WrappedCipherLT(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLT(FieldWrappedCipher, v))
}

// WrappedCipherLTE applies the LTE predicate on the "wrapped_cipher" field.
func WrappedCipherLTE(v []byte) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLTE(FieldWrappedCipher, v))
}

// AllowedEQ applies the EQ predicate on the "allowed" field.
func AllowedEQ(v bool) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldAllowed, v))
}

// AllowedNEQ applies the NEQ predicate on the "allowed" field.
func AllowedNEQ(v bool) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNEQ(FieldAllowed, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasLedgerAccounts applies the HasEdge predicate on the "ledger_accounts" edge.
func HasLedgerAccounts() predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedgerAccountsTable, LedgerAccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerAccountsWith applies the HasEdge predicate on the "ledger_accounts" edge with a given conditions (other predicates).
func HasLedgerAccountsWith(preds ...predicate.LedgerAccount) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(func(s *sql.Selector) {
		step := newLedgerAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LedgerEncryptionKey) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LedgerEncryptionKey) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LedgerEncryptionKey) predicate.LedgerEncryptionKey {
	return predicate.LedgerEncryptionKey(sql.NotPredicates(p))
}
