name: Detect Files Changed

on:
  workflow_call:
    outputs:
      go:
        value: ${{ jobs.detect.outputs.go }}
      ts:
        value: ${{ jobs.detect.outputs.ts }}

permissions:
  contents: read
  pull-requests: read

jobs:
  detect:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      go: ${{ steps.changes.outputs.go_any_modified == 'true' || steps.changes.outputs.ci_any_modified == 'true' }}
      ts: ${{ steps.changes.outputs.ts_any_modified == 'true' || steps.changes.outputs.ci_any_modified == 'true' }}
    steps:
      - uses: actions/checkout@v6.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: tj-actions/changed-files@v47
        id: changes
        with:
          files_yaml: |
            go:
              - go/**/*

            ts:
              - ts/**/*

            ci:
              - .github/workflows/**/*
